# 운영환경(main branch)에서 사용하는 docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.zeroone.it.kr
    restart: unless-stopped
