# 운영환경(main branch)에서 사용하는 Dockerfile

# 1단계: build
FROM node:20-alpine AS builder
WORKDIR /app

COPY . .

# 빌드시점에 .env 파일 복사 
COPY .env .env

RUN yarn install && yarn build --no-lint

# 2단계: production
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/yarn.lock ./yarn.lock
COPY --from=builder /app/next.config.ts ./next.config.ts

# 런타임시점에도 .env 파일 복사
COPY --from=builder /app/.env .env

# 빌드 시 Node 힙 메모리를 4GB까지 허용 (4096 = 4GB)
ENV NODE_OPTIONS="--max-old-space-size=4096"

# devDependencies는 설치하지 않고 dependencies만 설치
RUN yarn install --production 

# 포트 설정 (prod 환경)
ENV PORT=13755
EXPOSE 13755

CMD ["yarn", "start"]
