/**
 * 액세스 토큰 세션을 검증하거나 재발급하는 과정에서 발생할 수 있는 실패 이유다.
 * 미들웨어는 이 값을 기준으로 후속 쿠키 정리 정책을 결정한다.
 */
export const ACCESS_TOKEN_SESSION_FAILURE_REASONS = {
  REFRESH_FAILED: '리프레시 토큰으로 액세스 토큰을 재발급하지 못함',
  REFRESH_REQUEST_FAILED: '리프레시 토큰 재발급 요청 자체가 실패함',
  TOKEN_VERIFY_FAILED: '액세스 토큰 검증에 실패함',
  VERIFY_REQUEST_FAILED: '액세스 토큰 검증 요청 자체가 실패함',
  MISSING_MEMBER_ID_FOR_NON_GUEST:
    '게스트가 아닌데 memberId 없이 액세스 토큰만 남아 있음',
  MISSING_ROLE_IDS_FOR_AUTHENTICATED_TOKEN:
    '정식 회원 액세스 토큰인데 roleIds claim을 해석할 수 없음',
} as const;

export type AccessTokenSessionFailureReason =
  (typeof ACCESS_TOKEN_SESSION_FAILURE_REASONS)[keyof typeof ACCESS_TOKEN_SESSION_FAILURE_REASONS];

/**
 * 세션 정리 시 로그에 남기는 이유다.
 * 값 자체가 로그/디버깅에서 읽히도록 한국어 문장으로 유지한다.
 */
export const AUTH_COOKIE_CLEAR_REASONS = {
  IDENTITY_COOKIE_WITHOUT_ACCESS_TOKEN:
    '액세스 토큰 없이 식별용 쿠키만 남아 있음',
  LOGIN_ROUTE_REFRESH_FAILED: '로그인 페이지에서 액세스 토큰 재발급에 실패함',
  LOGIN_ROUTE_REFRESH_REQUEST_FAILED:
    '로그인 페이지에서 액세스 토큰 재발급 요청에 실패함',
  LOGIN_ROUTE_TOKEN_VERIFY_FAILED:
    '로그인 페이지에서 액세스 토큰 검증에 실패함',
  LOGIN_ROUTE_VERIFY_REQUEST_FAILED:
    '로그인 페이지에서 액세스 토큰 검증 요청에 실패함',
  LOGIN_ROUTE_MISSING_MEMBER_ID:
    '로그인 페이지에서 게스트가 아닌데 memberId 없는 세션이 남아 있음',
  LOGIN_ROUTE_MISSING_ROLE_IDS:
    '로그인 페이지에서 roleIds 없는 정식 회원 세션이 남아 있음',
  SIGN_UP_ROUTE_REFRESH_FAILED:
    '회원가입 페이지에서 액세스 토큰 재발급에 실패함',
  SIGN_UP_ROUTE_REFRESH_REQUEST_FAILED:
    '회원가입 페이지에서 액세스 토큰 재발급 요청에 실패함',
  SIGN_UP_ROUTE_TOKEN_VERIFY_FAILED:
    '회원가입 페이지에서 액세스 토큰 검증에 실패함',
  SIGN_UP_ROUTE_VERIFY_REQUEST_FAILED:
    '회원가입 페이지에서 액세스 토큰 검증 요청에 실패함',
  SIGN_UP_ROUTE_MISSING_MEMBER_ID:
    '회원가입 페이지에서 게스트가 아닌데 memberId 없는 세션이 남아 있음',
  SIGN_UP_ROUTE_MISSING_ROLE_IDS:
    '회원가입 페이지에서 roleIds 없는 정식 회원 세션이 남아 있음',
  PROTECTED_ROUTE_MISSING_MEMBER_ID:
    '보호 경로에서 memberId 없이 세션이 남아 있음',
  PROTECTED_ROUTE_MISSING_ROLE_IDS:
    '보호 경로에서 roleIds 없는 정식 회원 세션이 남아 있음',
  PROTECTED_ROUTE_REFRESH_FAILED: '보호 경로에서 액세스 토큰 재발급에 실패함',
  PROTECTED_ROUTE_REFRESH_REQUEST_FAILED:
    '보호 경로에서 액세스 토큰 재발급 요청에 실패함',
  PROTECTED_ROUTE_TOKEN_VERIFY_FAILED:
    '보호 경로에서 액세스 토큰 검증에 실패함',
  PROTECTED_ROUTE_VERIFY_REQUEST_FAILED:
    '보호 경로에서 액세스 토큰 검증 요청에 실패함',
  PUBLIC_ROUTE_MISSING_MEMBER_ID:
    '공개 경로에서 게스트가 아닌데 memberId 없는 세션이 남아 있음',
  PUBLIC_ROUTE_MISSING_ROLE_IDS:
    '공개 경로에서 roleIds 없는 정식 회원 세션이 남아 있음',
  PUBLIC_ROUTE_REFRESH_FAILED: '공개 경로에서 액세스 토큰 재발급에 실패함',
  PUBLIC_ROUTE_REFRESH_REQUEST_FAILED:
    '공개 경로에서 액세스 토큰 재발급 요청에 실패함',
  PUBLIC_ROUTE_TOKEN_VERIFY_FAILED: '공개 경로에서 액세스 토큰 검증에 실패함',
  PUBLIC_ROUTE_VERIFY_REQUEST_FAILED:
    '공개 경로에서 액세스 토큰 검증 요청에 실패함',
} as const;

export type AuthCookieClearReason =
  (typeof AUTH_COOKIE_CLEAR_REASONS)[keyof typeof AUTH_COOKIE_CLEAR_REASONS];

export const isTransientAccessTokenSessionFailureReason = (
  reason: AccessTokenSessionFailureReason,
): boolean =>
  reason === ACCESS_TOKEN_SESSION_FAILURE_REASONS.VERIFY_REQUEST_FAILED ||
  reason === ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_REQUEST_FAILED;

export const PUBLIC_ROUTE_CLEAR_REASON_BY_FAILURE: Partial<
  Record<AccessTokenSessionFailureReason, AuthCookieClearReason>
> = {
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.PUBLIC_ROUTE_REFRESH_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.TOKEN_VERIFY_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.PUBLIC_ROUTE_TOKEN_VERIFY_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_MEMBER_ID_FOR_NON_GUEST]:
    AUTH_COOKIE_CLEAR_REASONS.PUBLIC_ROUTE_MISSING_MEMBER_ID,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_ROLE_IDS_FOR_AUTHENTICATED_TOKEN]:
    AUTH_COOKIE_CLEAR_REASONS.PUBLIC_ROUTE_MISSING_ROLE_IDS,
};

export const SIGN_UP_ROUTE_CLEAR_REASON_BY_FAILURE: Record<
  AccessTokenSessionFailureReason,
  AuthCookieClearReason
> = {
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.SIGN_UP_ROUTE_REFRESH_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_REQUEST_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.SIGN_UP_ROUTE_REFRESH_REQUEST_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.TOKEN_VERIFY_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.SIGN_UP_ROUTE_TOKEN_VERIFY_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.VERIFY_REQUEST_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.SIGN_UP_ROUTE_VERIFY_REQUEST_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_MEMBER_ID_FOR_NON_GUEST]:
    AUTH_COOKIE_CLEAR_REASONS.SIGN_UP_ROUTE_MISSING_MEMBER_ID,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_ROLE_IDS_FOR_AUTHENTICATED_TOKEN]:
    AUTH_COOKIE_CLEAR_REASONS.SIGN_UP_ROUTE_MISSING_ROLE_IDS,
};

export const LOGIN_ROUTE_CLEAR_REASON_BY_FAILURE: Record<
  AccessTokenSessionFailureReason,
  AuthCookieClearReason
> = {
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.LOGIN_ROUTE_REFRESH_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_REQUEST_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.LOGIN_ROUTE_REFRESH_REQUEST_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.TOKEN_VERIFY_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.LOGIN_ROUTE_TOKEN_VERIFY_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.VERIFY_REQUEST_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.LOGIN_ROUTE_VERIFY_REQUEST_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_MEMBER_ID_FOR_NON_GUEST]:
    AUTH_COOKIE_CLEAR_REASONS.LOGIN_ROUTE_MISSING_MEMBER_ID,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_ROLE_IDS_FOR_AUTHENTICATED_TOKEN]:
    AUTH_COOKIE_CLEAR_REASONS.LOGIN_ROUTE_MISSING_ROLE_IDS,
};

export const PROTECTED_ROUTE_CLEAR_REASON_BY_FAILURE: Record<
  AccessTokenSessionFailureReason,
  AuthCookieClearReason
> = {
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.PROTECTED_ROUTE_REFRESH_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.REFRESH_REQUEST_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.PROTECTED_ROUTE_REFRESH_REQUEST_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.TOKEN_VERIFY_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.PROTECTED_ROUTE_TOKEN_VERIFY_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.VERIFY_REQUEST_FAILED]:
    AUTH_COOKIE_CLEAR_REASONS.PROTECTED_ROUTE_VERIFY_REQUEST_FAILED,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_MEMBER_ID_FOR_NON_GUEST]:
    AUTH_COOKIE_CLEAR_REASONS.PROTECTED_ROUTE_MISSING_MEMBER_ID,
  [ACCESS_TOKEN_SESSION_FAILURE_REASONS.MISSING_ROLE_IDS_FOR_AUTHENTICATED_TOKEN]:
    AUTH_COOKIE_CLEAR_REASONS.PROTECTED_ROUTE_MISSING_ROLE_IDS,
};
