/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseClassAlerttalkDryRunResponse } from '../models';
// @ts-ignore
import type { BaseResponseClassAlerttalkLogDetailResponse } from '../models';
// @ts-ignore
import type { BaseResponseClassAlerttalkRetryResponse } from '../models';
// @ts-ignore
import type { BaseResponseClassAlerttalkTemplateListResponse } from '../models';
// @ts-ignore
import type { BaseResponseClassAlerttalkTemplateSyncResponse } from '../models';
// @ts-ignore
import type { BaseResponseClassAlerttalkTestSendResponse } from '../models';
// @ts-ignore
import type { BaseResponseListClassAlerttalkLogResponse } from '../models';
// @ts-ignore
import type { ClassAlerttalkDryRunRequest } from '../models';
// @ts-ignore
import type { ClassAlerttalkRetryRequest } from '../models';
// @ts-ignore
import type { ClassAlerttalkTemplateSyncRequest } from '../models';
// @ts-ignore
import type { ClassAlerttalkTemplateTestSendRequest } from '../models';
// @ts-ignore
import type { ClassAlerttalkTestSendRequest } from '../models';
/**
 * AdminAlerttalkControllerApi - axios parameter creator
 */
export const AdminAlerttalkControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ClassAlerttalkDryRunRequest} classAlerttalkDryRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dryRun: async (classAlerttalkDryRunRequest: ClassAlerttalkDryRunRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classAlerttalkDryRunRequest' is not null or undefined
            assertParamExists('dryRun', 'classAlerttalkDryRunRequest', classAlerttalkDryRunRequest)
            const localVarPath = `/api/v5/admin/alerttalk/schedules/dry-run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classAlerttalkDryRunRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogDetail: async (jobId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getLogDetail', 'jobId', jobId)
            const localVarPath = `/api/v5/admin/alerttalk/delivery-logs/{jobId}`
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [templateKey] 
         * @param {string} [status] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogs: async (templateKey?: string, status?: string, from?: string, to?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v5/admin/alerttalk/delivery-logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (templateKey !== undefined) {
                localVarQueryParameter['templateKey'] = templateKey;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [templateKey] 
         * @param {string} [approvalStatus] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplates: async (templateKey?: string, approvalStatus?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v5/admin/alerttalk/templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (templateKey !== undefined) {
                localVarQueryParameter['templateKey'] = templateKey;
            }

            if (approvalStatus !== undefined) {
                localVarQueryParameter['approvalStatus'] = approvalStatus;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} jobId 
         * @param {ClassAlerttalkRetryRequest} [classAlerttalkRetryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retry: async (jobId: number, classAlerttalkRetryRequest?: ClassAlerttalkRetryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('retry', 'jobId', jobId)
            const localVarPath = `/api/v5/admin/alerttalk/delivery-logs/{jobId}/retry`
                .replace(`{${"jobId"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classAlerttalkRetryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ClassAlerttalkTemplateSyncRequest} [classAlerttalkTemplateSyncRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncTemplates1: async (classAlerttalkTemplateSyncRequest?: ClassAlerttalkTemplateSyncRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v5/admin/alerttalk/templates/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classAlerttalkTemplateSyncRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ClassAlerttalkTestSendRequest} classAlerttalkTestSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testSend: async (classAlerttalkTestSendRequest: ClassAlerttalkTestSendRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classAlerttalkTestSendRequest' is not null or undefined
            assertParamExists('testSend', 'classAlerttalkTestSendRequest', classAlerttalkTestSendRequest)
            const localVarPath = `/api/v5/admin/alerttalk/test-send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classAlerttalkTestSendRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} templateKey 
         * @param {ClassAlerttalkTemplateTestSendRequest} classAlerttalkTemplateTestSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testSendByTemplate: async (templateKey: string, classAlerttalkTemplateTestSendRequest: ClassAlerttalkTemplateTestSendRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'templateKey' is not null or undefined
            assertParamExists('testSendByTemplate', 'templateKey', templateKey)
            // verify required parameter 'classAlerttalkTemplateTestSendRequest' is not null or undefined
            assertParamExists('testSendByTemplate', 'classAlerttalkTemplateTestSendRequest', classAlerttalkTemplateTestSendRequest)
            const localVarPath = `/api/v5/admin/alerttalk/templates/{templateKey}/test-send`
                .replace(`{${"templateKey"}}`, encodeURIComponent(String(templateKey)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classAlerttalkTemplateTestSendRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminAlerttalkControllerApi - functional programming interface
 */
export const AdminAlerttalkControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminAlerttalkControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ClassAlerttalkDryRunRequest} classAlerttalkDryRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dryRun(classAlerttalkDryRunRequest: ClassAlerttalkDryRunRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseClassAlerttalkDryRunResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dryRun(classAlerttalkDryRunRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.dryRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLogDetail(jobId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseClassAlerttalkLogDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLogDetail(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.getLogDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [templateKey] 
         * @param {string} [status] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLogs(templateKey?: string, status?: string, from?: string, to?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseListClassAlerttalkLogResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLogs(templateKey, status, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.getLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [templateKey] 
         * @param {string} [approvalStatus] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplates(templateKey?: string, approvalStatus?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseClassAlerttalkTemplateListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplates(templateKey, approvalStatus, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.getTemplates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} jobId 
         * @param {ClassAlerttalkRetryRequest} [classAlerttalkRetryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retry(jobId: number, classAlerttalkRetryRequest?: ClassAlerttalkRetryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseClassAlerttalkRetryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retry(jobId, classAlerttalkRetryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.retry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ClassAlerttalkTemplateSyncRequest} [classAlerttalkTemplateSyncRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncTemplates1(classAlerttalkTemplateSyncRequest?: ClassAlerttalkTemplateSyncRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseClassAlerttalkTemplateSyncResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncTemplates1(classAlerttalkTemplateSyncRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.syncTemplates1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ClassAlerttalkTestSendRequest} classAlerttalkTestSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testSend(classAlerttalkTestSendRequest: ClassAlerttalkTestSendRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseClassAlerttalkTestSendResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testSend(classAlerttalkTestSendRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.testSend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} templateKey 
         * @param {ClassAlerttalkTemplateTestSendRequest} classAlerttalkTemplateTestSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async testSendByTemplate(templateKey: string, classAlerttalkTemplateTestSendRequest: ClassAlerttalkTemplateTestSendRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseClassAlerttalkTestSendResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testSendByTemplate(templateKey, classAlerttalkTemplateTestSendRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAlerttalkControllerApi.testSendByTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminAlerttalkControllerApi - factory interface
 */
export const AdminAlerttalkControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminAlerttalkControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ClassAlerttalkDryRunRequest} classAlerttalkDryRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dryRun(classAlerttalkDryRunRequest: ClassAlerttalkDryRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseClassAlerttalkDryRunResponse> {
            return localVarFp.dryRun(classAlerttalkDryRunRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogDetail(jobId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseClassAlerttalkLogDetailResponse> {
            return localVarFp.getLogDetail(jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [templateKey] 
         * @param {string} [status] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogs(templateKey?: string, status?: string, from?: string, to?: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseListClassAlerttalkLogResponse> {
            return localVarFp.getLogs(templateKey, status, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [templateKey] 
         * @param {string} [approvalStatus] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplates(templateKey?: string, approvalStatus?: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseClassAlerttalkTemplateListResponse> {
            return localVarFp.getTemplates(templateKey, approvalStatus, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} jobId 
         * @param {ClassAlerttalkRetryRequest} [classAlerttalkRetryRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retry(jobId: number, classAlerttalkRetryRequest?: ClassAlerttalkRetryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseClassAlerttalkRetryResponse> {
            return localVarFp.retry(jobId, classAlerttalkRetryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ClassAlerttalkTemplateSyncRequest} [classAlerttalkTemplateSyncRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncTemplates1(classAlerttalkTemplateSyncRequest?: ClassAlerttalkTemplateSyncRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseClassAlerttalkTemplateSyncResponse> {
            return localVarFp.syncTemplates1(classAlerttalkTemplateSyncRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ClassAlerttalkTestSendRequest} classAlerttalkTestSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testSend(classAlerttalkTestSendRequest: ClassAlerttalkTestSendRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseClassAlerttalkTestSendResponse> {
            return localVarFp.testSend(classAlerttalkTestSendRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} templateKey 
         * @param {ClassAlerttalkTemplateTestSendRequest} classAlerttalkTemplateTestSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testSendByTemplate(templateKey: string, classAlerttalkTemplateTestSendRequest: ClassAlerttalkTemplateTestSendRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseClassAlerttalkTestSendResponse> {
            return localVarFp.testSendByTemplate(templateKey, classAlerttalkTemplateTestSendRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminAlerttalkControllerApi - object-oriented interface
 */
export class AdminAlerttalkControllerApi extends BaseAPI {
    /**
     * 
     * @param {ClassAlerttalkDryRunRequest} classAlerttalkDryRunRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dryRun(classAlerttalkDryRunRequest: ClassAlerttalkDryRunRequest, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).dryRun(classAlerttalkDryRunRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} jobId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLogDetail(jobId: number, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).getLogDetail(jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [templateKey] 
     * @param {string} [status] 
     * @param {string} [from] 
     * @param {string} [to] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLogs(templateKey?: string, status?: string, from?: string, to?: string, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).getLogs(templateKey, status, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [templateKey] 
     * @param {string} [approvalStatus] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTemplates(templateKey?: string, approvalStatus?: string, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).getTemplates(templateKey, approvalStatus, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} jobId 
     * @param {ClassAlerttalkRetryRequest} [classAlerttalkRetryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retry(jobId: number, classAlerttalkRetryRequest?: ClassAlerttalkRetryRequest, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).retry(jobId, classAlerttalkRetryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ClassAlerttalkTemplateSyncRequest} [classAlerttalkTemplateSyncRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public syncTemplates1(classAlerttalkTemplateSyncRequest?: ClassAlerttalkTemplateSyncRequest, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).syncTemplates1(classAlerttalkTemplateSyncRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ClassAlerttalkTestSendRequest} classAlerttalkTestSendRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testSend(classAlerttalkTestSendRequest: ClassAlerttalkTestSendRequest, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).testSend(classAlerttalkTestSendRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} templateKey 
     * @param {ClassAlerttalkTemplateTestSendRequest} classAlerttalkTemplateTestSendRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public testSendByTemplate(templateKey: string, classAlerttalkTemplateTestSendRequest: ClassAlerttalkTemplateTestSendRequest, options?: RawAxiosRequestConfig) {
        return AdminAlerttalkControllerApiFp(this.configuration).testSendByTemplate(templateKey, classAlerttalkTemplateTestSendRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

