/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminMatchingCreateRequest } from '../models';
// @ts-ignore
import type { AdminMatchingUpdateRequest } from '../models';
// @ts-ignore
import type { AutoRunMatchingRequestDto } from '../models';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { ResetWeeklyMatchingRequest } from '../models';
// @ts-ignore
import type { ResetWeeklyMatchingSchema } from '../models';
/**
 * AdminMatchingApi - axios parameter creator
 */
export const AdminMatchingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 관리자가 수동으로 매칭 요청을 생성합니다. weeklyPeriodIdentifier는 매칭이 속할 주간을 지정하며, 해당 주간의 토요일 날짜를 사용합니다.
         * @summary 관리자 매칭 생성
         * @param {AdminMatchingCreateRequest} adminMatchingCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMatchingRequestByAdmin: async (adminMatchingCreateRequest: AdminMatchingCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adminMatchingCreateRequest' is not null or undefined
            assertParamExists('createMatchingRequestByAdmin', 'adminMatchingCreateRequest', adminMatchingCreateRequest)
            const localVarPath = `/api/v1/admin/matching/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminMatchingCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 관리자가 특정 매칭 요청을 논리적으로 삭제합니다.
         * @summary 관리자 매칭 삭제
         * @param {number} matchingRequestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMatchingRequestByAdmin: async (matchingRequestId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'matchingRequestId' is not null or undefined
            assertParamExists('deleteMatchingRequestByAdmin', 'matchingRequestId', matchingRequestId)
            const localVarPath = `/api/v1/admin/matching/requests/{matchingRequestId}`
                .replace(`{${"matchingRequestId"}}`, encodeURIComponent(String(matchingRequestId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 진행 중인 스터디 사이클을 종료하고, 다음 스터디 참여자 모집 상태로 변경합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**
         * @summary 스터디 사이클 종료
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endStudyCycle: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/matching/end-cycle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 관리자가 특정 매칭 요청을 조회합니다.
         * @summary 관리자 매칭 상세 조회
         * @param {number} matchingRequestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchingRequest: async (matchingRequestId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'matchingRequestId' is not null or undefined
            assertParamExists('getMatchingRequest', 'matchingRequestId', matchingRequestId)
            const localVarPath = `/api/v1/admin/matching/requests/{matchingRequestId}`
                .replace(`{${"matchingRequestId"}}`, encodeURIComponent(String(matchingRequestId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 주차의 모든 매칭 관련 데이터를 삭제합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  1. 출석 (attendance) - 가장 먼저 삭제 2. 데일리 스터디 (daily_study) 3. 스터디 멤버 (study_member) 4. 매칭 요청 파트너 결과 (matching_request_partner) 5. 매칭 요청 (matching_request) 6. 스터디 스페이스 (study_space) - 가장 마지막에 삭제  **주의사항:** - 트랜잭션 내에서 실행되며, 실패 시 자동 롤백됩니다 - 삭제된 데이터 건수가 응답으로 반환됩니다 - 해당 주차에 데이터가 없는 경우에도 성공으로 처리됩니다 (삭제 건수가 0) 
         * @summary 주차 매칭 데이터 초기화
         * @param {ResetWeeklyMatchingRequest} resetWeeklyMatchingRequest 초기화할 주차의 식별자
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetWeeklyMatching: async (resetWeeklyMatchingRequest: ResetWeeklyMatchingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resetWeeklyMatchingRequest' is not null or undefined
            assertParamExists('resetWeeklyMatching', 'resetWeeklyMatchingRequest', resetWeeklyMatchingRequest)
            const localVarPath = `/api/v1/admin/matching/reset-weekly`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resetWeeklyMatchingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 자동 매칭 배치 작업을 수동으로 시작합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  실행하는 관리자는 Bearer 토큰으로 식별됩니다. **파라미터 동작 방식:** - `targetWeek`: \'CURRENT\' 또는 \'NEXT\'를 지정하여 각각 이번 주 또는 다음 주의 매칭을 실행합니다. (기본값: NEXT) - `adminId`: 매칭 후 홀로 남는 사용자와 매칭될 \'땜빵\' 관리자 ID입니다. **수동 실행 시에는 이 필드가 필수입니다.** - `templateType`: 사용할 매칭 템플릿을 지정합니다. STUDY(학습 우선), TIME(시간 우선), RANDOM(랜덤) 중 선택. (기본값: STUDY) - 나머지 파라미터(`matchingKValue`, `chunkSize` 등)는 선택 사항입니다.   - 값을 제공하면 해당 값으로 Job이 실행됩니다.   - 값을 제공하지 않으면, 시스템이 현재 매칭 대상자 수를 기반으로 최적의 값을 **자동으로 계산**하여 실행합니다. 
         * @summary 자동 매칭 수동 트리거
         * @param {AutoRunMatchingRequestDto} autoRunMatchingRequestDto 자동 매칭 실행 파라미터. 값을 제공하지 않으면 시스템이 자동으로 최적의 값을 계산합니다.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runAutoMatchingJob: async (autoRunMatchingRequestDto: AutoRunMatchingRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'autoRunMatchingRequestDto' is not null or undefined
            assertParamExists('runAutoMatchingJob', 'autoRunMatchingRequestDto', autoRunMatchingRequestDto)
            const localVarPath = `/api/v1/admin/matching/run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(autoRunMatchingRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 관리자가 특정 매칭 요청의 상태, 파트너 등을 변경합니다.
         * @summary 관리자 매칭 변경/취소
         * @param {number} matchingRequestId 
         * @param {AdminMatchingUpdateRequest} adminMatchingUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMatchingRequestByAdmin: async (matchingRequestId: number, adminMatchingUpdateRequest: AdminMatchingUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'matchingRequestId' is not null or undefined
            assertParamExists('updateMatchingRequestByAdmin', 'matchingRequestId', matchingRequestId)
            // verify required parameter 'adminMatchingUpdateRequest' is not null or undefined
            assertParamExists('updateMatchingRequestByAdmin', 'adminMatchingUpdateRequest', adminMatchingUpdateRequest)
            const localVarPath = `/api/v1/admin/matching/requests/{matchingRequestId}`
                .replace(`{${"matchingRequestId"}}`, encodeURIComponent(String(matchingRequestId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminMatchingUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminMatchingApi - functional programming interface
 */
export const AdminMatchingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminMatchingApiAxiosParamCreator(configuration)
    return {
        /**
         * 관리자가 수동으로 매칭 요청을 생성합니다. weeklyPeriodIdentifier는 매칭이 속할 주간을 지정하며, 해당 주간의 토요일 날짜를 사용합니다.
         * @summary 관리자 매칭 생성
         * @param {AdminMatchingCreateRequest} adminMatchingCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMatchingRequestByAdmin(adminMatchingCreateRequest: AdminMatchingCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMatchingRequestByAdmin(adminMatchingCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMatchingApi.createMatchingRequestByAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 관리자가 특정 매칭 요청을 논리적으로 삭제합니다.
         * @summary 관리자 매칭 삭제
         * @param {number} matchingRequestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMatchingRequestByAdmin(matchingRequestId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMatchingRequestByAdmin(matchingRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMatchingApi.deleteMatchingRequestByAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 진행 중인 스터디 사이클을 종료하고, 다음 스터디 참여자 모집 상태로 변경합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**
         * @summary 스터디 사이클 종료
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async endStudyCycle(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.endStudyCycle(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMatchingApi.endStudyCycle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 관리자가 특정 매칭 요청을 조회합니다.
         * @summary 관리자 매칭 상세 조회
         * @param {number} matchingRequestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMatchingRequest(matchingRequestId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMatchingRequest(matchingRequestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMatchingApi.getMatchingRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 주차의 모든 매칭 관련 데이터를 삭제합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  1. 출석 (attendance) - 가장 먼저 삭제 2. 데일리 스터디 (daily_study) 3. 스터디 멤버 (study_member) 4. 매칭 요청 파트너 결과 (matching_request_partner) 5. 매칭 요청 (matching_request) 6. 스터디 스페이스 (study_space) - 가장 마지막에 삭제  **주의사항:** - 트랜잭션 내에서 실행되며, 실패 시 자동 롤백됩니다 - 삭제된 데이터 건수가 응답으로 반환됩니다 - 해당 주차에 데이터가 없는 경우에도 성공으로 처리됩니다 (삭제 건수가 0) 
         * @summary 주차 매칭 데이터 초기화
         * @param {ResetWeeklyMatchingRequest} resetWeeklyMatchingRequest 초기화할 주차의 식별자
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetWeeklyMatching(resetWeeklyMatchingRequest: ResetWeeklyMatchingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResetWeeklyMatchingSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetWeeklyMatching(resetWeeklyMatchingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMatchingApi.resetWeeklyMatching']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 자동 매칭 배치 작업을 수동으로 시작합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  실행하는 관리자는 Bearer 토큰으로 식별됩니다. **파라미터 동작 방식:** - `targetWeek`: \'CURRENT\' 또는 \'NEXT\'를 지정하여 각각 이번 주 또는 다음 주의 매칭을 실행합니다. (기본값: NEXT) - `adminId`: 매칭 후 홀로 남는 사용자와 매칭될 \'땜빵\' 관리자 ID입니다. **수동 실행 시에는 이 필드가 필수입니다.** - `templateType`: 사용할 매칭 템플릿을 지정합니다. STUDY(학습 우선), TIME(시간 우선), RANDOM(랜덤) 중 선택. (기본값: STUDY) - 나머지 파라미터(`matchingKValue`, `chunkSize` 등)는 선택 사항입니다.   - 값을 제공하면 해당 값으로 Job이 실행됩니다.   - 값을 제공하지 않으면, 시스템이 현재 매칭 대상자 수를 기반으로 최적의 값을 **자동으로 계산**하여 실행합니다. 
         * @summary 자동 매칭 수동 트리거
         * @param {AutoRunMatchingRequestDto} autoRunMatchingRequestDto 자동 매칭 실행 파라미터. 값을 제공하지 않으면 시스템이 자동으로 최적의 값을 계산합니다.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runAutoMatchingJob(autoRunMatchingRequestDto: AutoRunMatchingRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runAutoMatchingJob(autoRunMatchingRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMatchingApi.runAutoMatchingJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 관리자가 특정 매칭 요청의 상태, 파트너 등을 변경합니다.
         * @summary 관리자 매칭 변경/취소
         * @param {number} matchingRequestId 
         * @param {AdminMatchingUpdateRequest} adminMatchingUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMatchingRequestByAdmin(matchingRequestId: number, adminMatchingUpdateRequest: AdminMatchingUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMatchingRequestByAdmin(matchingRequestId, adminMatchingUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMatchingApi.updateMatchingRequestByAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminMatchingApi - factory interface
 */
export const AdminMatchingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminMatchingApiFp(configuration)
    return {
        /**
         * 관리자가 수동으로 매칭 요청을 생성합니다. weeklyPeriodIdentifier는 매칭이 속할 주간을 지정하며, 해당 주간의 토요일 날짜를 사용합니다.
         * @summary 관리자 매칭 생성
         * @param {AdminMatchingCreateRequest} adminMatchingCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMatchingRequestByAdmin(adminMatchingCreateRequest: AdminMatchingCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.createMatchingRequestByAdmin(adminMatchingCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 관리자가 특정 매칭 요청을 논리적으로 삭제합니다.
         * @summary 관리자 매칭 삭제
         * @param {number} matchingRequestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMatchingRequestByAdmin(matchingRequestId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteMatchingRequestByAdmin(matchingRequestId, options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 진행 중인 스터디 사이클을 종료하고, 다음 스터디 참여자 모집 상태로 변경합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**
         * @summary 스터디 사이클 종료
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endStudyCycle(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.endStudyCycle(options).then((request) => request(axios, basePath));
        },
        /**
         * 관리자가 특정 매칭 요청을 조회합니다.
         * @summary 관리자 매칭 상세 조회
         * @param {number} matchingRequestId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchingRequest(matchingRequestId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.getMatchingRequest(matchingRequestId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 주차의 모든 매칭 관련 데이터를 삭제합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  1. 출석 (attendance) - 가장 먼저 삭제 2. 데일리 스터디 (daily_study) 3. 스터디 멤버 (study_member) 4. 매칭 요청 파트너 결과 (matching_request_partner) 5. 매칭 요청 (matching_request) 6. 스터디 스페이스 (study_space) - 가장 마지막에 삭제  **주의사항:** - 트랜잭션 내에서 실행되며, 실패 시 자동 롤백됩니다 - 삭제된 데이터 건수가 응답으로 반환됩니다 - 해당 주차에 데이터가 없는 경우에도 성공으로 처리됩니다 (삭제 건수가 0) 
         * @summary 주차 매칭 데이터 초기화
         * @param {ResetWeeklyMatchingRequest} resetWeeklyMatchingRequest 초기화할 주차의 식별자
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetWeeklyMatching(resetWeeklyMatchingRequest: ResetWeeklyMatchingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResetWeeklyMatchingSchema> {
            return localVarFp.resetWeeklyMatching(resetWeeklyMatchingRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 자동 매칭 배치 작업을 수동으로 시작합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  실행하는 관리자는 Bearer 토큰으로 식별됩니다. **파라미터 동작 방식:** - `targetWeek`: \'CURRENT\' 또는 \'NEXT\'를 지정하여 각각 이번 주 또는 다음 주의 매칭을 실행합니다. (기본값: NEXT) - `adminId`: 매칭 후 홀로 남는 사용자와 매칭될 \'땜빵\' 관리자 ID입니다. **수동 실행 시에는 이 필드가 필수입니다.** - `templateType`: 사용할 매칭 템플릿을 지정합니다. STUDY(학습 우선), TIME(시간 우선), RANDOM(랜덤) 중 선택. (기본값: STUDY) - 나머지 파라미터(`matchingKValue`, `chunkSize` 등)는 선택 사항입니다.   - 값을 제공하면 해당 값으로 Job이 실행됩니다.   - 값을 제공하지 않으면, 시스템이 현재 매칭 대상자 수를 기반으로 최적의 값을 **자동으로 계산**하여 실행합니다. 
         * @summary 자동 매칭 수동 트리거
         * @param {AutoRunMatchingRequestDto} autoRunMatchingRequestDto 자동 매칭 실행 파라미터. 값을 제공하지 않으면 시스템이 자동으로 최적의 값을 계산합니다.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runAutoMatchingJob(autoRunMatchingRequestDto: AutoRunMatchingRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.runAutoMatchingJob(autoRunMatchingRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 관리자가 특정 매칭 요청의 상태, 파트너 등을 변경합니다.
         * @summary 관리자 매칭 변경/취소
         * @param {number} matchingRequestId 
         * @param {AdminMatchingUpdateRequest} adminMatchingUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMatchingRequestByAdmin(matchingRequestId: number, adminMatchingUpdateRequest: AdminMatchingUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.updateMatchingRequestByAdmin(matchingRequestId, adminMatchingUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminMatchingApi - object-oriented interface
 */
export class AdminMatchingApi extends BaseAPI {
    /**
     * 관리자가 수동으로 매칭 요청을 생성합니다. weeklyPeriodIdentifier는 매칭이 속할 주간을 지정하며, 해당 주간의 토요일 날짜를 사용합니다.
     * @summary 관리자 매칭 생성
     * @param {AdminMatchingCreateRequest} adminMatchingCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createMatchingRequestByAdmin(adminMatchingCreateRequest: AdminMatchingCreateRequest, options?: RawAxiosRequestConfig) {
        return AdminMatchingApiFp(this.configuration).createMatchingRequestByAdmin(adminMatchingCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 관리자가 특정 매칭 요청을 논리적으로 삭제합니다.
     * @summary 관리자 매칭 삭제
     * @param {number} matchingRequestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteMatchingRequestByAdmin(matchingRequestId: number, options?: RawAxiosRequestConfig) {
        return AdminMatchingApiFp(this.configuration).deleteMatchingRequestByAdmin(matchingRequestId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 진행 중인 스터디 사이클을 종료하고, 다음 스터디 참여자 모집 상태로 변경합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**
     * @summary 스터디 사이클 종료
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public endStudyCycle(options?: RawAxiosRequestConfig) {
        return AdminMatchingApiFp(this.configuration).endStudyCycle(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 관리자가 특정 매칭 요청을 조회합니다.
     * @summary 관리자 매칭 상세 조회
     * @param {number} matchingRequestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMatchingRequest(matchingRequestId: number, options?: RawAxiosRequestConfig) {
        return AdminMatchingApiFp(this.configuration).getMatchingRequest(matchingRequestId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 주차의 모든 매칭 관련 데이터를 삭제합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  1. 출석 (attendance) - 가장 먼저 삭제 2. 데일리 스터디 (daily_study) 3. 스터디 멤버 (study_member) 4. 매칭 요청 파트너 결과 (matching_request_partner) 5. 매칭 요청 (matching_request) 6. 스터디 스페이스 (study_space) - 가장 마지막에 삭제  **주의사항:** - 트랜잭션 내에서 실행되며, 실패 시 자동 롤백됩니다 - 삭제된 데이터 건수가 응답으로 반환됩니다 - 해당 주차에 데이터가 없는 경우에도 성공으로 처리됩니다 (삭제 건수가 0) 
     * @summary 주차 매칭 데이터 초기화
     * @param {ResetWeeklyMatchingRequest} resetWeeklyMatchingRequest 초기화할 주차의 식별자
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resetWeeklyMatching(resetWeeklyMatchingRequest: ResetWeeklyMatchingRequest, options?: RawAxiosRequestConfig) {
        return AdminMatchingApiFp(this.configuration).resetWeeklyMatching(resetWeeklyMatchingRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 자동 매칭 배치 작업을 수동으로 시작합니다. **관리자 권한(ROLE_ADMIN)이 필요합니다.**  실행하는 관리자는 Bearer 토큰으로 식별됩니다. **파라미터 동작 방식:** - `targetWeek`: \'CURRENT\' 또는 \'NEXT\'를 지정하여 각각 이번 주 또는 다음 주의 매칭을 실행합니다. (기본값: NEXT) - `adminId`: 매칭 후 홀로 남는 사용자와 매칭될 \'땜빵\' 관리자 ID입니다. **수동 실행 시에는 이 필드가 필수입니다.** - `templateType`: 사용할 매칭 템플릿을 지정합니다. STUDY(학습 우선), TIME(시간 우선), RANDOM(랜덤) 중 선택. (기본값: STUDY) - 나머지 파라미터(`matchingKValue`, `chunkSize` 등)는 선택 사항입니다.   - 값을 제공하면 해당 값으로 Job이 실행됩니다.   - 값을 제공하지 않으면, 시스템이 현재 매칭 대상자 수를 기반으로 최적의 값을 **자동으로 계산**하여 실행합니다. 
     * @summary 자동 매칭 수동 트리거
     * @param {AutoRunMatchingRequestDto} autoRunMatchingRequestDto 자동 매칭 실행 파라미터. 값을 제공하지 않으면 시스템이 자동으로 최적의 값을 계산합니다.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runAutoMatchingJob(autoRunMatchingRequestDto: AutoRunMatchingRequestDto, options?: RawAxiosRequestConfig) {
        return AdminMatchingApiFp(this.configuration).runAutoMatchingJob(autoRunMatchingRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 관리자가 특정 매칭 요청의 상태, 파트너 등을 변경합니다.
     * @summary 관리자 매칭 변경/취소
     * @param {number} matchingRequestId 
     * @param {AdminMatchingUpdateRequest} adminMatchingUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateMatchingRequestByAdmin(matchingRequestId: number, adminMatchingUpdateRequest: AdminMatchingUpdateRequest, options?: RawAxiosRequestConfig) {
        return AdminMatchingApiFp(this.configuration).updateMatchingRequestByAdmin(matchingRequestId, adminMatchingUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

