/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommunityQnaCommentDeleteResponse } from '../models';
// @ts-ignore
import type { CommunityQnaCommentMutationResponse } from '../models';
// @ts-ignore
import type { CommunityQnaCommentPageResponse } from '../models';
// @ts-ignore
import type { CreateCommunityQnaCommentRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { UpdateCommunityQnaCommentRequest } from '../models';
/**
 * CommunityQnACommentsApi - axios parameter creator
 */
export const CommunityQnACommentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Idempotency-Key를 사용해 답변 댓글 리소스를 생성합니다.
         * @summary QnA 답변 댓글 생성
         * @param {number} answerId 
         * @param {string} idempotencyKey 
         * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityQnaAnswerComment: async (answerId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'answerId' is not null or undefined
            assertParamExists('createCommunityQnaAnswerComment', 'answerId', answerId)
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createCommunityQnaAnswerComment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'createCommunityQnaCommentRequest' is not null or undefined
            assertParamExists('createCommunityQnaAnswerComment', 'createCommunityQnaCommentRequest', createCommunityQnaCommentRequest)
            const localVarPath = `/api/v1/community/answers/{answerId}/comments`
                .replace(`{${"answerId"}}`, encodeURIComponent(String(answerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCommunityQnaCommentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Idempotency-Key를 사용해 질문 댓글 리소스를 생성합니다.
         * @summary QnA 질문 댓글 생성
         * @param {number} questionId 
         * @param {string} idempotencyKey 
         * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityQnaQuestionComment: async (questionId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('createCommunityQnaQuestionComment', 'questionId', questionId)
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createCommunityQnaQuestionComment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'createCommunityQnaCommentRequest' is not null or undefined
            assertParamExists('createCommunityQnaQuestionComment', 'createCommunityQnaCommentRequest', createCommunityQnaCommentRequest)
            const localVarPath = `/api/v1/community/questions/{questionId}/comments`
                .replace(`{${"questionId"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCommunityQnaCommentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If-Match revision을 사용해 QnA 댓글 리소스를 soft delete합니다.
         * @summary QnA 댓글 삭제
         * @param {number} commentId 
         * @param {string} ifMatch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCommunityQnaComment: async (commentId: number, ifMatch: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('deleteCommunityQnaComment', 'commentId', commentId)
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('deleteCommunityQnaComment', 'ifMatch', ifMatch)
            const localVarPath = `/api/v1/community/qna-comments/{commentId}`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 답변에 속한 댓글 목록을 페이지네이션으로 조회합니다.
         * @summary QnA 답변 댓글 목록 조회
         * @param {number} answerId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityQnaAnswerComments: async (answerId: number, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'answerId' is not null or undefined
            assertParamExists('getCommunityQnaAnswerComments', 'answerId', answerId)
            const localVarPath = `/api/v1/community/answers/{answerId}/comments`
                .replace(`{${"answerId"}}`, encodeURIComponent(String(answerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 질문에 속한 댓글 목록을 페이지네이션으로 조회합니다.
         * @summary QnA 질문 댓글 목록 조회
         * @param {number} questionId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityQnaQuestionComments: async (questionId: number, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('getCommunityQnaQuestionComments', 'questionId', questionId)
            const localVarPath = `/api/v1/community/questions/{questionId}/comments`
                .replace(`{${"questionId"}}`, encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If-Match revision을 사용해 QnA 댓글 리소스를 수정합니다.
         * @summary QnA 댓글 수정
         * @param {number} commentId 
         * @param {string} ifMatch 
         * @param {UpdateCommunityQnaCommentRequest} updateCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCommunityQnaComment: async (commentId: number, ifMatch: string, updateCommunityQnaCommentRequest: UpdateCommunityQnaCommentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('updateCommunityQnaComment', 'commentId', commentId)
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('updateCommunityQnaComment', 'ifMatch', ifMatch)
            // verify required parameter 'updateCommunityQnaCommentRequest' is not null or undefined
            assertParamExists('updateCommunityQnaComment', 'updateCommunityQnaCommentRequest', updateCommunityQnaCommentRequest)
            const localVarPath = `/api/v1/community/qna-comments/{commentId}`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCommunityQnaCommentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommunityQnACommentsApi - functional programming interface
 */
export const CommunityQnACommentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommunityQnACommentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Idempotency-Key를 사용해 답변 댓글 리소스를 생성합니다.
         * @summary QnA 답변 댓글 생성
         * @param {number} answerId 
         * @param {string} idempotencyKey 
         * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCommunityQnaAnswerComment(answerId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityQnaCommentMutationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCommunityQnaAnswerComment(answerId, idempotencyKey, createCommunityQnaCommentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityQnACommentsApi.createCommunityQnaAnswerComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Idempotency-Key를 사용해 질문 댓글 리소스를 생성합니다.
         * @summary QnA 질문 댓글 생성
         * @param {number} questionId 
         * @param {string} idempotencyKey 
         * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCommunityQnaQuestionComment(questionId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityQnaCommentMutationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCommunityQnaQuestionComment(questionId, idempotencyKey, createCommunityQnaCommentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityQnACommentsApi.createCommunityQnaQuestionComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If-Match revision을 사용해 QnA 댓글 리소스를 soft delete합니다.
         * @summary QnA 댓글 삭제
         * @param {number} commentId 
         * @param {string} ifMatch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCommunityQnaComment(commentId: number, ifMatch: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityQnaCommentDeleteResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCommunityQnaComment(commentId, ifMatch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityQnACommentsApi.deleteCommunityQnaComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 답변에 속한 댓글 목록을 페이지네이션으로 조회합니다.
         * @summary QnA 답변 댓글 목록 조회
         * @param {number} answerId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommunityQnaAnswerComments(answerId: number, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityQnaCommentPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCommunityQnaAnswerComments(answerId, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityQnACommentsApi.getCommunityQnaAnswerComments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 질문에 속한 댓글 목록을 페이지네이션으로 조회합니다.
         * @summary QnA 질문 댓글 목록 조회
         * @param {number} questionId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommunityQnaQuestionComments(questionId: number, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityQnaCommentPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCommunityQnaQuestionComments(questionId, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityQnACommentsApi.getCommunityQnaQuestionComments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If-Match revision을 사용해 QnA 댓글 리소스를 수정합니다.
         * @summary QnA 댓글 수정
         * @param {number} commentId 
         * @param {string} ifMatch 
         * @param {UpdateCommunityQnaCommentRequest} updateCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCommunityQnaComment(commentId: number, ifMatch: string, updateCommunityQnaCommentRequest: UpdateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityQnaCommentMutationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCommunityQnaComment(commentId, ifMatch, updateCommunityQnaCommentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityQnACommentsApi.updateCommunityQnaComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CommunityQnACommentsApi - factory interface
 */
export const CommunityQnACommentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommunityQnACommentsApiFp(configuration)
    return {
        /**
         * Idempotency-Key를 사용해 답변 댓글 리소스를 생성합니다.
         * @summary QnA 답변 댓글 생성
         * @param {number} answerId 
         * @param {string} idempotencyKey 
         * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityQnaAnswerComment(answerId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunityQnaCommentMutationResponse> {
            return localVarFp.createCommunityQnaAnswerComment(answerId, idempotencyKey, createCommunityQnaCommentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Idempotency-Key를 사용해 질문 댓글 리소스를 생성합니다.
         * @summary QnA 질문 댓글 생성
         * @param {number} questionId 
         * @param {string} idempotencyKey 
         * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityQnaQuestionComment(questionId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunityQnaCommentMutationResponse> {
            return localVarFp.createCommunityQnaQuestionComment(questionId, idempotencyKey, createCommunityQnaCommentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * If-Match revision을 사용해 QnA 댓글 리소스를 soft delete합니다.
         * @summary QnA 댓글 삭제
         * @param {number} commentId 
         * @param {string} ifMatch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCommunityQnaComment(commentId: number, ifMatch: string, options?: RawAxiosRequestConfig): AxiosPromise<CommunityQnaCommentDeleteResponse> {
            return localVarFp.deleteCommunityQnaComment(commentId, ifMatch, options).then((request) => request(axios, basePath));
        },
        /**
         * 답변에 속한 댓글 목록을 페이지네이션으로 조회합니다.
         * @summary QnA 답변 댓글 목록 조회
         * @param {number} answerId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityQnaAnswerComments(answerId: number, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<CommunityQnaCommentPageResponse> {
            return localVarFp.getCommunityQnaAnswerComments(answerId, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 질문에 속한 댓글 목록을 페이지네이션으로 조회합니다.
         * @summary QnA 질문 댓글 목록 조회
         * @param {number} questionId 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityQnaQuestionComments(questionId: number, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<CommunityQnaCommentPageResponse> {
            return localVarFp.getCommunityQnaQuestionComments(questionId, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * If-Match revision을 사용해 QnA 댓글 리소스를 수정합니다.
         * @summary QnA 댓글 수정
         * @param {number} commentId 
         * @param {string} ifMatch 
         * @param {UpdateCommunityQnaCommentRequest} updateCommunityQnaCommentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCommunityQnaComment(commentId: number, ifMatch: string, updateCommunityQnaCommentRequest: UpdateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunityQnaCommentMutationResponse> {
            return localVarFp.updateCommunityQnaComment(commentId, ifMatch, updateCommunityQnaCommentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CommunityQnACommentsApi - object-oriented interface
 */
export class CommunityQnACommentsApi extends BaseAPI {
    /**
     * Idempotency-Key를 사용해 답변 댓글 리소스를 생성합니다.
     * @summary QnA 답변 댓글 생성
     * @param {number} answerId 
     * @param {string} idempotencyKey 
     * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCommunityQnaAnswerComment(answerId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig) {
        return CommunityQnACommentsApiFp(this.configuration).createCommunityQnaAnswerComment(answerId, idempotencyKey, createCommunityQnaCommentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Idempotency-Key를 사용해 질문 댓글 리소스를 생성합니다.
     * @summary QnA 질문 댓글 생성
     * @param {number} questionId 
     * @param {string} idempotencyKey 
     * @param {CreateCommunityQnaCommentRequest} createCommunityQnaCommentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCommunityQnaQuestionComment(questionId: number, idempotencyKey: string, createCommunityQnaCommentRequest: CreateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig) {
        return CommunityQnACommentsApiFp(this.configuration).createCommunityQnaQuestionComment(questionId, idempotencyKey, createCommunityQnaCommentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If-Match revision을 사용해 QnA 댓글 리소스를 soft delete합니다.
     * @summary QnA 댓글 삭제
     * @param {number} commentId 
     * @param {string} ifMatch 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCommunityQnaComment(commentId: number, ifMatch: string, options?: RawAxiosRequestConfig) {
        return CommunityQnACommentsApiFp(this.configuration).deleteCommunityQnaComment(commentId, ifMatch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 답변에 속한 댓글 목록을 페이지네이션으로 조회합니다.
     * @summary QnA 답변 댓글 목록 조회
     * @param {number} answerId 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCommunityQnaAnswerComments(answerId: number, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return CommunityQnACommentsApiFp(this.configuration).getCommunityQnaAnswerComments(answerId, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 질문에 속한 댓글 목록을 페이지네이션으로 조회합니다.
     * @summary QnA 질문 댓글 목록 조회
     * @param {number} questionId 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCommunityQnaQuestionComments(questionId: number, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return CommunityQnACommentsApiFp(this.configuration).getCommunityQnaQuestionComments(questionId, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If-Match revision을 사용해 QnA 댓글 리소스를 수정합니다.
     * @summary QnA 댓글 수정
     * @param {number} commentId 
     * @param {string} ifMatch 
     * @param {UpdateCommunityQnaCommentRequest} updateCommunityQnaCommentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCommunityQnaComment(commentId: number, ifMatch: string, updateCommunityQnaCommentRequest: UpdateCommunityQnaCommentRequest, options?: RawAxiosRequestConfig) {
        return CommunityQnACommentsApiFp(this.configuration).updateCommunityQnaComment(commentId, ifMatch, updateCommunityQnaCommentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

