/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AssignCommunityPostReactionRequest } from '../models';
// @ts-ignore
import type { CommunityContentImageUploadTicketRequest } from '../models';
// @ts-ignore
import type { CommunityContentImageUploadTicketResponse } from '../models';
// @ts-ignore
import type { CommunityPostDetailResponse } from '../models';
// @ts-ignore
import type { CommunityPostFeedResponse } from '../models';
// @ts-ignore
import type { CommunityPostReactionResponse } from '../models';
// @ts-ignore
import type { CommunityPostSummaryListResponse } from '../models';
// @ts-ignore
import type { CommunityPostViewEventResponse } from '../models';
// @ts-ignore
import type { CreateCommunityPostRequest } from '../models';
// @ts-ignore
import type { DeleteCommunityPostResponse } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { UpdateCommunityPostRequest } from '../models';
/**
 * CommunityPostsApi - axios parameter creator
 */
export const CommunityPostsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 로그인 사용자가 커뮤니티 게시글에 like 또는 none 반응을 지정합니다.
         * @summary 커뮤니티 게시글 반응 지정
         * @param {number} postId 
         * @param {AssignCommunityPostReactionRequest} assignCommunityPostReactionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignCommunityPostReaction: async (postId: number, assignCommunityPostReactionRequest: AssignCommunityPostReactionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('assignCommunityPostReaction', 'postId', postId)
            // verify required parameter 'assignCommunityPostReactionRequest' is not null or undefined
            assertParamExists('assignCommunityPostReaction', 'assignCommunityPostReactionRequest', assignCommunityPostReactionRequest)
            const localVarPath = `/api/v1/community/posts/{postId}/reactions`
                .replace(`{${"postId"}}`, encodeURIComponent(String(postId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assignCommunityPostReactionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 로그인 사용자가 커뮤니티 게시글 본문 이미지 업로드용 티켓을 발급받습니다.
         * @summary 커뮤니티 본문 이미지 업로드 티켓 발급
         * @param {CommunityContentImageUploadTicketRequest} communityContentImageUploadTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityContentImageUploadTicket: async (communityContentImageUploadTicketRequest: CommunityContentImageUploadTicketRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'communityContentImageUploadTicketRequest' is not null or undefined
            assertParamExists('createCommunityContentImageUploadTicket', 'communityContentImageUploadTicketRequest', communityContentImageUploadTicketRequest)
            const localVarPath = `/api/v1/community/posts/content-images/upload-ticket`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(communityContentImageUploadTicketRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Idempotency-Key를 사용해 공개 커뮤니티 게시글을 생성합니다.
         * @summary 커뮤니티 게시글 생성
         * @param {string} idempotencyKey 
         * @param {CreateCommunityPostRequest} createCommunityPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityPost: async (idempotencyKey: string, createCommunityPostRequest: CreateCommunityPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createCommunityPost', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'createCommunityPostRequest' is not null or undefined
            assertParamExists('createCommunityPost', 'createCommunityPostRequest', createCommunityPostRequest)
            const localVarPath = `/api/v1/community/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCommunityPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If-Match revision을 검증하고 커뮤니티 게시글을 soft delete 처리합니다.
         * @summary 커뮤니티 게시글 삭제
         * @param {number} postId 
         * @param {string} ifMatch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCommunityPost: async (postId: number, ifMatch: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('deleteCommunityPost', 'postId', postId)
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('deleteCommunityPost', 'ifMatch', ifMatch)
            const localVarPath = `/api/v1/community/posts/{postId}`
                .replace(`{${"postId"}}`, encodeURIComponent(String(postId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 공개 상태의 커뮤니티 게시글 상세를 조회합니다.
         * @summary 커뮤니티 게시글 상세 조회
         * @param {number} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityPostDetail: async (postId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('getCommunityPostDetail', 'postId', postId)
            const localVarPath = `/api/v1/community/posts/{postId}`
                .replace(`{${"postId"}}`, encodeURIComponent(String(postId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * board/page/size 조건으로 공개 커뮤니티 목록을 조회합니다. board=all 인 경우 일반 게시글과 질문답변(QnA) 질문 summary를 함께 반환합니다. 
         * @summary 커뮤니티 게시글 목록 조회
         * @param {string} [board] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityPosts: async (board?: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/community/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (board !== undefined) {
                localVarQueryParameter['board'] = board;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기준 게시글과 연관된 공개 게시글 목록을 조회합니다.
         * @summary 커뮤니티 관련 글 조회
         * @param {number} postId 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRelatedCommunityPosts: async (postId: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('getRelatedCommunityPosts', 'postId', postId)
            const localVarPath = `/api/v1/community/posts/{postId}/related-posts`
                .replace(`{${"postId"}}`, encodeURIComponent(String(postId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 로그인 사용자 또는 익명 viewer key 기준으로 게시글 조회수를 기록합니다.
         * @summary 커뮤니티 게시글 조회수 이벤트 기록
         * @param {number} postId 
         * @param {string} [communityViewerKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordCommunityPostView: async (postId: number, communityViewerKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('recordCommunityPostView', 'postId', postId)
            const localVarPath = `/api/v1/community/posts/{postId}/views`
                .replace(`{${"postId"}}`, encodeURIComponent(String(postId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If-Match revision을 검증하고 커뮤니티 게시글을 수정합니다.
         * @summary 커뮤니티 게시글 수정
         * @param {number} postId 
         * @param {string} ifMatch 
         * @param {UpdateCommunityPostRequest} updateCommunityPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCommunityPost: async (postId: number, ifMatch: string, updateCommunityPostRequest: UpdateCommunityPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('updateCommunityPost', 'postId', postId)
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('updateCommunityPost', 'ifMatch', ifMatch)
            // verify required parameter 'updateCommunityPostRequest' is not null or undefined
            assertParamExists('updateCommunityPost', 'updateCommunityPostRequest', updateCommunityPostRequest)
            const localVarPath = `/api/v1/community/posts/{postId}`
                .replace(`{${"postId"}}`, encodeURIComponent(String(postId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCommunityPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommunityPostsApi - functional programming interface
 */
export const CommunityPostsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommunityPostsApiAxiosParamCreator(configuration)
    return {
        /**
         * 로그인 사용자가 커뮤니티 게시글에 like 또는 none 반응을 지정합니다.
         * @summary 커뮤니티 게시글 반응 지정
         * @param {number} postId 
         * @param {AssignCommunityPostReactionRequest} assignCommunityPostReactionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignCommunityPostReaction(postId: number, assignCommunityPostReactionRequest: AssignCommunityPostReactionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityPostReactionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignCommunityPostReaction(postId, assignCommunityPostReactionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.assignCommunityPostReaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 로그인 사용자가 커뮤니티 게시글 본문 이미지 업로드용 티켓을 발급받습니다.
         * @summary 커뮤니티 본문 이미지 업로드 티켓 발급
         * @param {CommunityContentImageUploadTicketRequest} communityContentImageUploadTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCommunityContentImageUploadTicket(communityContentImageUploadTicketRequest: CommunityContentImageUploadTicketRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityContentImageUploadTicketResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCommunityContentImageUploadTicket(communityContentImageUploadTicketRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.createCommunityContentImageUploadTicket']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Idempotency-Key를 사용해 공개 커뮤니티 게시글을 생성합니다.
         * @summary 커뮤니티 게시글 생성
         * @param {string} idempotencyKey 
         * @param {CreateCommunityPostRequest} createCommunityPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCommunityPost(idempotencyKey: string, createCommunityPostRequest: CreateCommunityPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityPostDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCommunityPost(idempotencyKey, createCommunityPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.createCommunityPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If-Match revision을 검증하고 커뮤니티 게시글을 soft delete 처리합니다.
         * @summary 커뮤니티 게시글 삭제
         * @param {number} postId 
         * @param {string} ifMatch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCommunityPost(postId: number, ifMatch: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteCommunityPostResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCommunityPost(postId, ifMatch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.deleteCommunityPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 공개 상태의 커뮤니티 게시글 상세를 조회합니다.
         * @summary 커뮤니티 게시글 상세 조회
         * @param {number} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommunityPostDetail(postId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityPostDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCommunityPostDetail(postId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.getCommunityPostDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * board/page/size 조건으로 공개 커뮤니티 목록을 조회합니다. board=all 인 경우 일반 게시글과 질문답변(QnA) 질문 summary를 함께 반환합니다. 
         * @summary 커뮤니티 게시글 목록 조회
         * @param {string} [board] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommunityPosts(board?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityPostFeedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCommunityPosts(board, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.getCommunityPosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기준 게시글과 연관된 공개 게시글 목록을 조회합니다.
         * @summary 커뮤니티 관련 글 조회
         * @param {number} postId 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRelatedCommunityPosts(postId: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityPostSummaryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRelatedCommunityPosts(postId, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.getRelatedCommunityPosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 로그인 사용자 또는 익명 viewer key 기준으로 게시글 조회수를 기록합니다.
         * @summary 커뮤니티 게시글 조회수 이벤트 기록
         * @param {number} postId 
         * @param {string} [communityViewerKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordCommunityPostView(postId: number, communityViewerKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityPostViewEventResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordCommunityPostView(postId, communityViewerKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.recordCommunityPostView']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If-Match revision을 검증하고 커뮤니티 게시글을 수정합니다.
         * @summary 커뮤니티 게시글 수정
         * @param {number} postId 
         * @param {string} ifMatch 
         * @param {UpdateCommunityPostRequest} updateCommunityPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCommunityPost(postId: number, ifMatch: string, updateCommunityPostRequest: UpdateCommunityPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommunityPostDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCommunityPost(postId, ifMatch, updateCommunityPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommunityPostsApi.updateCommunityPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CommunityPostsApi - factory interface
 */
export const CommunityPostsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommunityPostsApiFp(configuration)
    return {
        /**
         * 로그인 사용자가 커뮤니티 게시글에 like 또는 none 반응을 지정합니다.
         * @summary 커뮤니티 게시글 반응 지정
         * @param {number} postId 
         * @param {AssignCommunityPostReactionRequest} assignCommunityPostReactionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignCommunityPostReaction(postId: number, assignCommunityPostReactionRequest: AssignCommunityPostReactionRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunityPostReactionResponse> {
            return localVarFp.assignCommunityPostReaction(postId, assignCommunityPostReactionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 로그인 사용자가 커뮤니티 게시글 본문 이미지 업로드용 티켓을 발급받습니다.
         * @summary 커뮤니티 본문 이미지 업로드 티켓 발급
         * @param {CommunityContentImageUploadTicketRequest} communityContentImageUploadTicketRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityContentImageUploadTicket(communityContentImageUploadTicketRequest: CommunityContentImageUploadTicketRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunityContentImageUploadTicketResponse> {
            return localVarFp.createCommunityContentImageUploadTicket(communityContentImageUploadTicketRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Idempotency-Key를 사용해 공개 커뮤니티 게시글을 생성합니다.
         * @summary 커뮤니티 게시글 생성
         * @param {string} idempotencyKey 
         * @param {CreateCommunityPostRequest} createCommunityPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCommunityPost(idempotencyKey: string, createCommunityPostRequest: CreateCommunityPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunityPostDetailResponse> {
            return localVarFp.createCommunityPost(idempotencyKey, createCommunityPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * If-Match revision을 검증하고 커뮤니티 게시글을 soft delete 처리합니다.
         * @summary 커뮤니티 게시글 삭제
         * @param {number} postId 
         * @param {string} ifMatch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCommunityPost(postId: number, ifMatch: string, options?: RawAxiosRequestConfig): AxiosPromise<DeleteCommunityPostResponse> {
            return localVarFp.deleteCommunityPost(postId, ifMatch, options).then((request) => request(axios, basePath));
        },
        /**
         * 공개 상태의 커뮤니티 게시글 상세를 조회합니다.
         * @summary 커뮤니티 게시글 상세 조회
         * @param {number} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityPostDetail(postId: number, options?: RawAxiosRequestConfig): AxiosPromise<CommunityPostDetailResponse> {
            return localVarFp.getCommunityPostDetail(postId, options).then((request) => request(axios, basePath));
        },
        /**
         * board/page/size 조건으로 공개 커뮤니티 목록을 조회합니다. board=all 인 경우 일반 게시글과 질문답변(QnA) 질문 summary를 함께 반환합니다. 
         * @summary 커뮤니티 게시글 목록 조회
         * @param {string} [board] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommunityPosts(board?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<CommunityPostFeedResponse> {
            return localVarFp.getCommunityPosts(board, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 기준 게시글과 연관된 공개 게시글 목록을 조회합니다.
         * @summary 커뮤니티 관련 글 조회
         * @param {number} postId 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRelatedCommunityPosts(postId: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<CommunityPostSummaryListResponse> {
            return localVarFp.getRelatedCommunityPosts(postId, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 로그인 사용자 또는 익명 viewer key 기준으로 게시글 조회수를 기록합니다.
         * @summary 커뮤니티 게시글 조회수 이벤트 기록
         * @param {number} postId 
         * @param {string} [communityViewerKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordCommunityPostView(postId: number, communityViewerKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommunityPostViewEventResponse> {
            return localVarFp.recordCommunityPostView(postId, communityViewerKey, options).then((request) => request(axios, basePath));
        },
        /**
         * If-Match revision을 검증하고 커뮤니티 게시글을 수정합니다.
         * @summary 커뮤니티 게시글 수정
         * @param {number} postId 
         * @param {string} ifMatch 
         * @param {UpdateCommunityPostRequest} updateCommunityPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCommunityPost(postId: number, ifMatch: string, updateCommunityPostRequest: UpdateCommunityPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommunityPostDetailResponse> {
            return localVarFp.updateCommunityPost(postId, ifMatch, updateCommunityPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CommunityPostsApi - object-oriented interface
 */
export class CommunityPostsApi extends BaseAPI {
    /**
     * 로그인 사용자가 커뮤니티 게시글에 like 또는 none 반응을 지정합니다.
     * @summary 커뮤니티 게시글 반응 지정
     * @param {number} postId 
     * @param {AssignCommunityPostReactionRequest} assignCommunityPostReactionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignCommunityPostReaction(postId: number, assignCommunityPostReactionRequest: AssignCommunityPostReactionRequest, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).assignCommunityPostReaction(postId, assignCommunityPostReactionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 로그인 사용자가 커뮤니티 게시글 본문 이미지 업로드용 티켓을 발급받습니다.
     * @summary 커뮤니티 본문 이미지 업로드 티켓 발급
     * @param {CommunityContentImageUploadTicketRequest} communityContentImageUploadTicketRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCommunityContentImageUploadTicket(communityContentImageUploadTicketRequest: CommunityContentImageUploadTicketRequest, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).createCommunityContentImageUploadTicket(communityContentImageUploadTicketRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Idempotency-Key를 사용해 공개 커뮤니티 게시글을 생성합니다.
     * @summary 커뮤니티 게시글 생성
     * @param {string} idempotencyKey 
     * @param {CreateCommunityPostRequest} createCommunityPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCommunityPost(idempotencyKey: string, createCommunityPostRequest: CreateCommunityPostRequest, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).createCommunityPost(idempotencyKey, createCommunityPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If-Match revision을 검증하고 커뮤니티 게시글을 soft delete 처리합니다.
     * @summary 커뮤니티 게시글 삭제
     * @param {number} postId 
     * @param {string} ifMatch 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCommunityPost(postId: number, ifMatch: string, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).deleteCommunityPost(postId, ifMatch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 공개 상태의 커뮤니티 게시글 상세를 조회합니다.
     * @summary 커뮤니티 게시글 상세 조회
     * @param {number} postId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCommunityPostDetail(postId: number, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).getCommunityPostDetail(postId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * board/page/size 조건으로 공개 커뮤니티 목록을 조회합니다. board=all 인 경우 일반 게시글과 질문답변(QnA) 질문 summary를 함께 반환합니다. 
     * @summary 커뮤니티 게시글 목록 조회
     * @param {string} [board] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCommunityPosts(board?: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).getCommunityPosts(board, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기준 게시글과 연관된 공개 게시글 목록을 조회합니다.
     * @summary 커뮤니티 관련 글 조회
     * @param {number} postId 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRelatedCommunityPosts(postId: number, size?: number, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).getRelatedCommunityPosts(postId, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 로그인 사용자 또는 익명 viewer key 기준으로 게시글 조회수를 기록합니다.
     * @summary 커뮤니티 게시글 조회수 이벤트 기록
     * @param {number} postId 
     * @param {string} [communityViewerKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recordCommunityPostView(postId: number, communityViewerKey?: string, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).recordCommunityPostView(postId, communityViewerKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If-Match revision을 검증하고 커뮤니티 게시글을 수정합니다.
     * @summary 커뮤니티 게시글 수정
     * @param {number} postId 
     * @param {string} ifMatch 
     * @param {UpdateCommunityPostRequest} updateCommunityPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCommunityPost(postId: number, ifMatch: string, updateCommunityPostRequest: UpdateCommunityPostRequest, options?: RawAxiosRequestConfig) {
        return CommunityPostsApiFp(this.configuration).updateCommunityPost(postId, ifMatch, updateCommunityPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

