/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { UploadProfileImageRequest } from '../models';
/**
 * FileControllerApi - axios parameter creator
 */
export const FileControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} filePath 
         * @param {string} fileClassification 
         * @param {UploadProfileImageRequest} [uploadProfileImageRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadProfileImage: async (filePath: string, fileClassification: string, uploadProfileImageRequest?: UploadProfileImageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'filePath' is not null or undefined
            assertParamExists('uploadProfileImage', 'filePath', filePath)
            // verify required parameter 'fileClassification' is not null or undefined
            assertParamExists('uploadProfileImage', 'fileClassification', fileClassification)
            const localVarPath = `/api/v1/files/{filePath}`
                .replace(`{${"filePath"}}`, encodeURIComponent(String(filePath)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (fileClassification !== undefined) {
                localVarQueryParameter['file-classification'] = fileClassification;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadProfileImageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FileControllerApi - functional programming interface
 */
export const FileControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FileControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} filePath 
         * @param {string} fileClassification 
         * @param {UploadProfileImageRequest} [uploadProfileImageRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadProfileImage(filePath: string, fileClassification: string, uploadProfileImageRequest?: UploadProfileImageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadProfileImage(filePath, fileClassification, uploadProfileImageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FileControllerApi.uploadProfileImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FileControllerApi - factory interface
 */
export const FileControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FileControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} filePath 
         * @param {string} fileClassification 
         * @param {UploadProfileImageRequest} [uploadProfileImageRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadProfileImage(filePath: string, fileClassification: string, uploadProfileImageRequest?: UploadProfileImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.uploadProfileImage(filePath, fileClassification, uploadProfileImageRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FileControllerApi - object-oriented interface
 */
export class FileControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} filePath 
     * @param {string} fileClassification 
     * @param {UploadProfileImageRequest} [uploadProfileImageRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadProfileImage(filePath: string, fileClassification: string, uploadProfileImageRequest?: UploadProfileImageRequest, options?: RawAxiosRequestConfig) {
        return FileControllerApiFp(this.configuration).uploadProfileImage(filePath, fileClassification, uploadProfileImageRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

