/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GroupStudyCreationRequestDto } from '../models';
// @ts-ignore
import type { GroupStudyFullResponseDto } from '../models';
// @ts-ignore
import type { GroupStudyInterviewPostRequestDto } from '../models';
// @ts-ignore
import type { GroupStudyUpdateRequestDto } from '../models';
// @ts-ignore
import type { PageResponseDto } from '../models';
/**
 * GroupStudyManagementApi - axios parameter creator
 */
export const GroupStudyManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 그룹스터디 상태를 COMPLETED로 변경합니다.  [권한] - 🔐 로그인 필수 (ROLE_MEMBER) - 👤 해당 그룹스터디 리더만 가능
         * @summary 그룹스터디 종료
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeGroupStudy: async (groupStudyId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupStudyId' is not null or undefined
            assertParamExists('completeGroupStudy', 'groupStudyId', groupStudyId)
            const localVarPath = `/api/v1/group-studies/{groupStudyId}/complete`
                .replace(`{${"groupStudyId"}}`, encodeURIComponent(String(groupStudyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 새로운 그룹스터디를 생성합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - Bearer Token이 필요합니다. 
         * @summary 그룹스터디 생성
         * @param {GroupStudyCreationRequestDto} groupStudyCreationRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGroupStudy: async (groupStudyCreationRequestDto: GroupStudyCreationRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupStudyCreationRequestDto' is not null or undefined
            assertParamExists('createGroupStudy', 'groupStudyCreationRequestDto', groupStudyCreationRequestDto)
            const localVarPath = `/api/v1/group-studies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(groupStudyCreationRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 그룹스터디를 삭제합니다. 본인이 생성한 그룹스터디만 삭제할 수 있습니다.
         * @summary 그룹스터디 삭제
         * @param {number} groupStudyId 삭제할 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGroupStudy: async (groupStudyId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupStudyId' is not null or undefined
            assertParamExists('deleteGroupStudy', 'groupStudyId', groupStudyId)
            const localVarPath = `/api/v1/group-studies/{groupStudyId}`
                .replace(`{${"groupStudyId"}}`, encodeURIComponent(String(groupStudyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 모든 그룹스터디 목록을 조회합니다. 다양한 조건으로 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
         * @summary 그룹스터디 목록 조회
         * @param {GetGroupStudiesClassificationEnum} classification 스터디 분류 (일반 그룹 스터디 / 프리미엄 스터디)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [pageSize] 페이지 크기
         * @param {Array<GetGroupStudiesTypeEnum>} [type] 스터디 종류 필터 (PROJECT: 프로젝트, STUDY: 스터디). 다중 선택 가능.
         * @param {Array<GetGroupStudiesTargetRolesEnum>} [targetRoles] 모집 대상 역할 필터 (PLANNER: 기획자, BACKEND: 백엔드 개발자, FRONTEND: 프론트엔드 개발자, DESIGNER: 디자이너, ANY: 무관). 다중 선택 가능.
         * @param {Array<GetGroupStudiesMethodEnum>} [method] 진행 방식 필터 (ONLINE: 온라인, OFFLINE: 오프라인, BOTH: 병행). 다중 선택 가능.
         * @param {boolean} [inProgress] 진행중인 스터디만 조회할지 여부.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupStudies: async (classification: GetGroupStudiesClassificationEnum, page?: number, pageSize?: number, type?: Array<GetGroupStudiesTypeEnum>, targetRoles?: Array<GetGroupStudiesTargetRolesEnum>, method?: Array<GetGroupStudiesMethodEnum>, inProgress?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classification' is not null or undefined
            assertParamExists('getGroupStudies', 'classification', classification)
            const localVarPath = `/api/v1/group-studies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page-size'] = pageSize;
            }

            if (classification !== undefined) {
                localVarQueryParameter['classification'] = classification;
            }

            if (type) {
                localVarQueryParameter['type'] = type;
            }

            if (targetRoles) {
                localVarQueryParameter['target-roles'] = targetRoles;
            }

            if (method) {
                localVarQueryParameter['method'] = method;
            }

            if (inProgress !== undefined) {
                localVarQueryParameter['in-progress'] = inProgress;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 그룹스터디의 상세 정보를 조회합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
         * @summary 그룹스터디 상세 조회
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupStudy: async (groupStudyId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupStudyId' is not null or undefined
            assertParamExists('getGroupStudy', 'groupStudyId', groupStudyId)
            const localVarPath = `/api/v1/group-studies/{groupStudyId}`
                .replace(`{${"groupStudyId"}}`, encodeURIComponent(String(groupStudyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 신청자가 신청한 활성 그룹스터디 목록을 조회합니다. 삭제되지 않은 신청만 조회되며, 상태별 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - URL의 applicantId로 누구나 조회 가능합니다. 
         * @summary 내가 신청한 그룹스터디 목록 조회
         * @param {number} applicantId 신청자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [pageSize] 페이지 크기
         * @param {GetMyGroupStudyApplicationsApplyStatusEnum} [applyStatus] 신청 상태 필터 (선택사항) - PENDING, APPROVED, REJECTED, EXIT, KICKED 중 선택, 생략시 모든 상태 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyGroupStudyApplications: async (applicantId: number, page?: number, pageSize?: number, applyStatus?: GetMyGroupStudyApplicationsApplyStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'applicantId' is not null or undefined
            assertParamExists('getMyGroupStudyApplications', 'applicantId', applicantId)
            const localVarPath = `/api/v1/group-studies/applicants/{applicantId}/applies`
                .replace(`{${"applicantId"}}`, encodeURIComponent(String(applicantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page-size'] = pageSize;
            }

            if (applyStatus !== undefined) {
                localVarQueryParameter['applyStatus'] = applyStatus;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 그룹스터디의 기본 정보(타입, 모집인원, 진행방식 등), 상세 정보(제목, 설명, 요약, 썸네일), 개설질문을 한번에 수정합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - 👤 **그룹스터디 리더만** 수정 가능 
         * @summary 그룹스터디 정보 수정 (기본정보 + 상세정보 + 개설질문)
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {GroupStudyUpdateRequestDto} groupStudyUpdateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGroupStudyInfo: async (groupStudyId: number, groupStudyUpdateRequestDto: GroupStudyUpdateRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupStudyId' is not null or undefined
            assertParamExists('updateGroupStudyInfo', 'groupStudyId', groupStudyId)
            // verify required parameter 'groupStudyUpdateRequestDto' is not null or undefined
            assertParamExists('updateGroupStudyInfo', 'groupStudyUpdateRequestDto', groupStudyUpdateRequestDto)
            const localVarPath = `/api/v1/group-studies/{groupStudyId}`
                .replace(`{${"groupStudyId"}}`, encodeURIComponent(String(groupStudyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(groupStudyUpdateRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 그룹스터디의 개설질문을 수정합니다.
         * @summary 그룹스터디 개설질문 수정
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {GroupStudyInterviewPostRequestDto} groupStudyInterviewPostRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGroupStudyInterviewPost: async (groupStudyId: number, groupStudyInterviewPostRequestDto: GroupStudyInterviewPostRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupStudyId' is not null or undefined
            assertParamExists('updateGroupStudyInterviewPost', 'groupStudyId', groupStudyId)
            // verify required parameter 'groupStudyInterviewPostRequestDto' is not null or undefined
            assertParamExists('updateGroupStudyInterviewPost', 'groupStudyInterviewPostRequestDto', groupStudyInterviewPostRequestDto)
            const localVarPath = `/api/v1/group-studies/{groupStudyId}/interview-post`
                .replace(`{${"groupStudyId"}}`, encodeURIComponent(String(groupStudyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(groupStudyInterviewPostRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupStudyManagementApi - functional programming interface
 */
export const GroupStudyManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GroupStudyManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 그룹스터디 상태를 COMPLETED로 변경합니다.  [권한] - 🔐 로그인 필수 (ROLE_MEMBER) - 👤 해당 그룹스터디 리더만 가능
         * @summary 그룹스터디 종료
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async completeGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.completeGroupStudy(groupStudyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.completeGroupStudy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 새로운 그룹스터디를 생성합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - Bearer Token이 필요합니다. 
         * @summary 그룹스터디 생성
         * @param {GroupStudyCreationRequestDto} groupStudyCreationRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createGroupStudy(groupStudyCreationRequestDto: GroupStudyCreationRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createGroupStudy(groupStudyCreationRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.createGroupStudy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 그룹스터디를 삭제합니다. 본인이 생성한 그룹스터디만 삭제할 수 있습니다.
         * @summary 그룹스터디 삭제
         * @param {number} groupStudyId 삭제할 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteGroupStudy(groupStudyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.deleteGroupStudy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 모든 그룹스터디 목록을 조회합니다. 다양한 조건으로 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
         * @summary 그룹스터디 목록 조회
         * @param {GetGroupStudiesClassificationEnum} classification 스터디 분류 (일반 그룹 스터디 / 프리미엄 스터디)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [pageSize] 페이지 크기
         * @param {Array<GetGroupStudiesTypeEnum>} [type] 스터디 종류 필터 (PROJECT: 프로젝트, STUDY: 스터디). 다중 선택 가능.
         * @param {Array<GetGroupStudiesTargetRolesEnum>} [targetRoles] 모집 대상 역할 필터 (PLANNER: 기획자, BACKEND: 백엔드 개발자, FRONTEND: 프론트엔드 개발자, DESIGNER: 디자이너, ANY: 무관). 다중 선택 가능.
         * @param {Array<GetGroupStudiesMethodEnum>} [method] 진행 방식 필터 (ONLINE: 온라인, OFFLINE: 오프라인, BOTH: 병행). 다중 선택 가능.
         * @param {boolean} [inProgress] 진행중인 스터디만 조회할지 여부.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupStudies(classification: GetGroupStudiesClassificationEnum, page?: number, pageSize?: number, type?: Array<GetGroupStudiesTypeEnum>, targetRoles?: Array<GetGroupStudiesTargetRolesEnum>, method?: Array<GetGroupStudiesMethodEnum>, inProgress?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroupStudies(classification, page, pageSize, type, targetRoles, method, inProgress, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.getGroupStudies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 그룹스터디의 상세 정보를 조회합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
         * @summary 그룹스터디 상세 조회
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupStudyFullResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroupStudy(groupStudyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.getGroupStudy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 신청자가 신청한 활성 그룹스터디 목록을 조회합니다. 삭제되지 않은 신청만 조회되며, 상태별 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - URL의 applicantId로 누구나 조회 가능합니다. 
         * @summary 내가 신청한 그룹스터디 목록 조회
         * @param {number} applicantId 신청자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [pageSize] 페이지 크기
         * @param {GetMyGroupStudyApplicationsApplyStatusEnum} [applyStatus] 신청 상태 필터 (선택사항) - PENDING, APPROVED, REJECTED, EXIT, KICKED 중 선택, 생략시 모든 상태 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyGroupStudyApplications(applicantId: number, page?: number, pageSize?: number, applyStatus?: GetMyGroupStudyApplicationsApplyStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyGroupStudyApplications(applicantId, page, pageSize, applyStatus, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.getMyGroupStudyApplications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 그룹스터디의 기본 정보(타입, 모집인원, 진행방식 등), 상세 정보(제목, 설명, 요약, 썸네일), 개설질문을 한번에 수정합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - 👤 **그룹스터디 리더만** 수정 가능 
         * @summary 그룹스터디 정보 수정 (기본정보 + 상세정보 + 개설질문)
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {GroupStudyUpdateRequestDto} groupStudyUpdateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateGroupStudyInfo(groupStudyId: number, groupStudyUpdateRequestDto: GroupStudyUpdateRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateGroupStudyInfo(groupStudyId, groupStudyUpdateRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.updateGroupStudyInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 그룹스터디의 개설질문을 수정합니다.
         * @summary 그룹스터디 개설질문 수정
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {GroupStudyInterviewPostRequestDto} groupStudyInterviewPostRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateGroupStudyInterviewPost(groupStudyId: number, groupStudyInterviewPostRequestDto: GroupStudyInterviewPostRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateGroupStudyInterviewPost(groupStudyId, groupStudyInterviewPostRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyManagementApi.updateGroupStudyInterviewPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GroupStudyManagementApi - factory interface
 */
export const GroupStudyManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GroupStudyManagementApiFp(configuration)
    return {
        /**
         * 그룹스터디 상태를 COMPLETED로 변경합니다.  [권한] - 🔐 로그인 필수 (ROLE_MEMBER) - 👤 해당 그룹스터디 리더만 가능
         * @summary 그룹스터디 종료
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.completeGroupStudy(groupStudyId, options).then((request) => request(axios, basePath));
        },
        /**
         * 새로운 그룹스터디를 생성합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - Bearer Token이 필요합니다. 
         * @summary 그룹스터디 생성
         * @param {GroupStudyCreationRequestDto} groupStudyCreationRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGroupStudy(groupStudyCreationRequestDto: GroupStudyCreationRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createGroupStudy(groupStudyCreationRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 그룹스터디를 삭제합니다. 본인이 생성한 그룹스터디만 삭제할 수 있습니다.
         * @summary 그룹스터디 삭제
         * @param {number} groupStudyId 삭제할 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteGroupStudy(groupStudyId, options).then((request) => request(axios, basePath));
        },
        /**
         * 모든 그룹스터디 목록을 조회합니다. 다양한 조건으로 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
         * @summary 그룹스터디 목록 조회
         * @param {GetGroupStudiesClassificationEnum} classification 스터디 분류 (일반 그룹 스터디 / 프리미엄 스터디)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [pageSize] 페이지 크기
         * @param {Array<GetGroupStudiesTypeEnum>} [type] 스터디 종류 필터 (PROJECT: 프로젝트, STUDY: 스터디). 다중 선택 가능.
         * @param {Array<GetGroupStudiesTargetRolesEnum>} [targetRoles] 모집 대상 역할 필터 (PLANNER: 기획자, BACKEND: 백엔드 개발자, FRONTEND: 프론트엔드 개발자, DESIGNER: 디자이너, ANY: 무관). 다중 선택 가능.
         * @param {Array<GetGroupStudiesMethodEnum>} [method] 진행 방식 필터 (ONLINE: 온라인, OFFLINE: 오프라인, BOTH: 병행). 다중 선택 가능.
         * @param {boolean} [inProgress] 진행중인 스터디만 조회할지 여부.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupStudies(classification: GetGroupStudiesClassificationEnum, page?: number, pageSize?: number, type?: Array<GetGroupStudiesTypeEnum>, targetRoles?: Array<GetGroupStudiesTargetRolesEnum>, method?: Array<GetGroupStudiesMethodEnum>, inProgress?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<PageResponseDto> {
            return localVarFp.getGroupStudies(classification, page, pageSize, type, targetRoles, method, inProgress, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 그룹스터디의 상세 정보를 조회합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
         * @summary 그룹스터디 상세 조회
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig): AxiosPromise<GroupStudyFullResponseDto> {
            return localVarFp.getGroupStudy(groupStudyId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 신청자가 신청한 활성 그룹스터디 목록을 조회합니다. 삭제되지 않은 신청만 조회되며, 상태별 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - URL의 applicantId로 누구나 조회 가능합니다. 
         * @summary 내가 신청한 그룹스터디 목록 조회
         * @param {number} applicantId 신청자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [pageSize] 페이지 크기
         * @param {GetMyGroupStudyApplicationsApplyStatusEnum} [applyStatus] 신청 상태 필터 (선택사항) - PENDING, APPROVED, REJECTED, EXIT, KICKED 중 선택, 생략시 모든 상태 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyGroupStudyApplications(applicantId: number, page?: number, pageSize?: number, applyStatus?: GetMyGroupStudyApplicationsApplyStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<PageResponseDto> {
            return localVarFp.getMyGroupStudyApplications(applicantId, page, pageSize, applyStatus, options).then((request) => request(axios, basePath));
        },
        /**
         * 그룹스터디의 기본 정보(타입, 모집인원, 진행방식 등), 상세 정보(제목, 설명, 요약, 썸네일), 개설질문을 한번에 수정합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - 👤 **그룹스터디 리더만** 수정 가능 
         * @summary 그룹스터디 정보 수정 (기본정보 + 상세정보 + 개설질문)
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {GroupStudyUpdateRequestDto} groupStudyUpdateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGroupStudyInfo(groupStudyId: number, groupStudyUpdateRequestDto: GroupStudyUpdateRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateGroupStudyInfo(groupStudyId, groupStudyUpdateRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 그룹스터디의 개설질문을 수정합니다.
         * @summary 그룹스터디 개설질문 수정
         * @param {number} groupStudyId 그룹스터디 ID
         * @param {GroupStudyInterviewPostRequestDto} groupStudyInterviewPostRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateGroupStudyInterviewPost(groupStudyId: number, groupStudyInterviewPostRequestDto: GroupStudyInterviewPostRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateGroupStudyInterviewPost(groupStudyId, groupStudyInterviewPostRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GroupStudyManagementApi - object-oriented interface
 */
export class GroupStudyManagementApi extends BaseAPI {
    /**
     * 그룹스터디 상태를 COMPLETED로 변경합니다.  [권한] - 🔐 로그인 필수 (ROLE_MEMBER) - 👤 해당 그룹스터디 리더만 가능
     * @summary 그룹스터디 종료
     * @param {number} groupStudyId 그룹스터디 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public completeGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).completeGroupStudy(groupStudyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 새로운 그룹스터디를 생성합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - Bearer Token이 필요합니다. 
     * @summary 그룹스터디 생성
     * @param {GroupStudyCreationRequestDto} groupStudyCreationRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createGroupStudy(groupStudyCreationRequestDto: GroupStudyCreationRequestDto, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).createGroupStudy(groupStudyCreationRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 그룹스터디를 삭제합니다. 본인이 생성한 그룹스터디만 삭제할 수 있습니다.
     * @summary 그룹스터디 삭제
     * @param {number} groupStudyId 삭제할 그룹스터디 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).deleteGroupStudy(groupStudyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 모든 그룹스터디 목록을 조회합니다. 다양한 조건으로 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
     * @summary 그룹스터디 목록 조회
     * @param {GetGroupStudiesClassificationEnum} classification 스터디 분류 (일반 그룹 스터디 / 프리미엄 스터디)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [pageSize] 페이지 크기
     * @param {Array<GetGroupStudiesTypeEnum>} [type] 스터디 종류 필터 (PROJECT: 프로젝트, STUDY: 스터디). 다중 선택 가능.
     * @param {Array<GetGroupStudiesTargetRolesEnum>} [targetRoles] 모집 대상 역할 필터 (PLANNER: 기획자, BACKEND: 백엔드 개발자, FRONTEND: 프론트엔드 개발자, DESIGNER: 디자이너, ANY: 무관). 다중 선택 가능.
     * @param {Array<GetGroupStudiesMethodEnum>} [method] 진행 방식 필터 (ONLINE: 온라인, OFFLINE: 오프라인, BOTH: 병행). 다중 선택 가능.
     * @param {boolean} [inProgress] 진행중인 스터디만 조회할지 여부.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGroupStudies(classification: GetGroupStudiesClassificationEnum, page?: number, pageSize?: number, type?: Array<GetGroupStudiesTypeEnum>, targetRoles?: Array<GetGroupStudiesTargetRolesEnum>, method?: Array<GetGroupStudiesMethodEnum>, inProgress?: boolean, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).getGroupStudies(classification, page, pageSize, type, targetRoles, method, inProgress, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 그룹스터디의 상세 정보를 조회합니다.  **[권한]** - 🌐 **비회원 접근 가능** - 로그인 없이 조회할 수 있습니다. 
     * @summary 그룹스터디 상세 조회
     * @param {number} groupStudyId 그룹스터디 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGroupStudy(groupStudyId: number, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).getGroupStudy(groupStudyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 신청자가 신청한 활성 그룹스터디 목록을 조회합니다. 삭제되지 않은 신청만 조회되며, 상태별 필터링이 가능합니다.  **[권한]** - 🌐 **비회원 접근 가능** - URL의 applicantId로 누구나 조회 가능합니다. 
     * @summary 내가 신청한 그룹스터디 목록 조회
     * @param {number} applicantId 신청자 ID
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [pageSize] 페이지 크기
     * @param {GetMyGroupStudyApplicationsApplyStatusEnum} [applyStatus] 신청 상태 필터 (선택사항) - PENDING, APPROVED, REJECTED, EXIT, KICKED 중 선택, 생략시 모든 상태 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyGroupStudyApplications(applicantId: number, page?: number, pageSize?: number, applyStatus?: GetMyGroupStudyApplicationsApplyStatusEnum, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).getMyGroupStudyApplications(applicantId, page, pageSize, applyStatus, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 그룹스터디의 기본 정보(타입, 모집인원, 진행방식 등), 상세 정보(제목, 설명, 요약, 썸네일), 개설질문을 한번에 수정합니다.  **[권한]** - 🔐 **로그인 필수** (ROLE_MEMBER) - 👤 **그룹스터디 리더만** 수정 가능 
     * @summary 그룹스터디 정보 수정 (기본정보 + 상세정보 + 개설질문)
     * @param {number} groupStudyId 그룹스터디 ID
     * @param {GroupStudyUpdateRequestDto} groupStudyUpdateRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateGroupStudyInfo(groupStudyId: number, groupStudyUpdateRequestDto: GroupStudyUpdateRequestDto, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).updateGroupStudyInfo(groupStudyId, groupStudyUpdateRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 그룹스터디의 개설질문을 수정합니다.
     * @summary 그룹스터디 개설질문 수정
     * @param {number} groupStudyId 그룹스터디 ID
     * @param {GroupStudyInterviewPostRequestDto} groupStudyInterviewPostRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateGroupStudyInterviewPost(groupStudyId: number, groupStudyInterviewPostRequestDto: GroupStudyInterviewPostRequestDto, options?: RawAxiosRequestConfig) {
        return GroupStudyManagementApiFp(this.configuration).updateGroupStudyInterviewPost(groupStudyId, groupStudyInterviewPostRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetGroupStudiesClassificationEnum = {
    GroupStudy: 'GROUP_STUDY',
    PremiumStudy: 'PREMIUM_STUDY'
} as const;
export type GetGroupStudiesClassificationEnum = typeof GetGroupStudiesClassificationEnum[keyof typeof GetGroupStudiesClassificationEnum];
export const GetGroupStudiesTypeEnum = {
    Project: 'PROJECT',
    Mentoring: 'MENTORING',
    Seminar: 'SEMINAR',
    Challenge: 'CHALLENGE',
    BookStudy: 'BOOK_STUDY',
    LectureStudy: 'LECTURE_STUDY'
} as const;
export type GetGroupStudiesTypeEnum = typeof GetGroupStudiesTypeEnum[keyof typeof GetGroupStudiesTypeEnum];
export const GetGroupStudiesTargetRolesEnum = {
    Backend: 'BACKEND',
    Frontend: 'FRONTEND',
    Planner: 'PLANNER',
    Designer: 'DESIGNER'
} as const;
export type GetGroupStudiesTargetRolesEnum = typeof GetGroupStudiesTargetRolesEnum[keyof typeof GetGroupStudiesTargetRolesEnum];
export const GetGroupStudiesMethodEnum = {
    Online: 'ONLINE',
    Offline: 'OFFLINE',
    Hybrid: 'HYBRID'
} as const;
export type GetGroupStudiesMethodEnum = typeof GetGroupStudiesMethodEnum[keyof typeof GetGroupStudiesMethodEnum];
export const GetMyGroupStudyApplicationsApplyStatusEnum = {
    None: 'NONE',
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Exit: 'EXIT',
    Kicked: 'KICKED'
} as const;
export type GetMyGroupStudyApplicationsApplyStatusEnum = typeof GetMyGroupStudyApplicationsApplyStatusEnum[keyof typeof GetMyGroupStudyApplicationsApplyStatusEnum];
