/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseHomeworkSubmissionResponse } from '../models';
// @ts-ignore
import type { BaseResponseVoid } from '../models';
// @ts-ignore
import type { HomeworkEditRequest } from '../models';
// @ts-ignore
import type { HomeworkSubmissionRequest } from '../models';
/**
 * GroupStudyHomeworkApi - axios parameter creator
 */
export const GroupStudyHomeworkApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} homeworkId 
         * @param {HomeworkEditRequest} homeworkEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editHomework: async (homeworkId: number, homeworkEditRequest: HomeworkEditRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'homeworkId' is not null or undefined
            assertParamExists('editHomework', 'homeworkId', homeworkId)
            // verify required parameter 'homeworkEditRequest' is not null or undefined
            assertParamExists('editHomework', 'homeworkEditRequest', homeworkEditRequest)
            const localVarPath = `/homeworks/{homeworkId}`
                .replace(`{${"homeworkId"}}`, encodeURIComponent(String(homeworkId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(homeworkEditRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} missionId 
         * @param {HomeworkSubmissionRequest} homeworkSubmissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitHomework: async (missionId: number, homeworkSubmissionRequest: HomeworkSubmissionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'missionId' is not null or undefined
            assertParamExists('submitHomework', 'missionId', missionId)
            // verify required parameter 'homeworkSubmissionRequest' is not null or undefined
            assertParamExists('submitHomework', 'homeworkSubmissionRequest', homeworkSubmissionRequest)
            const localVarPath = `/missions/{missionId}/homeworks`
                .replace(`{${"missionId"}}`, encodeURIComponent(String(missionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(homeworkSubmissionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupStudyHomeworkApi - functional programming interface
 */
export const GroupStudyHomeworkApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GroupStudyHomeworkApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} homeworkId 
         * @param {HomeworkEditRequest} homeworkEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editHomework(homeworkId: number, homeworkEditRequest: HomeworkEditRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editHomework(homeworkId, homeworkEditRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyHomeworkApi.editHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} missionId 
         * @param {HomeworkSubmissionRequest} homeworkSubmissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitHomework(missionId: number, homeworkSubmissionRequest: HomeworkSubmissionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseHomeworkSubmissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitHomework(missionId, homeworkSubmissionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupStudyHomeworkApi.submitHomework']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GroupStudyHomeworkApi - factory interface
 */
export const GroupStudyHomeworkApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GroupStudyHomeworkApiFp(configuration)
    return {
        /**
         * 
         * @param {number} homeworkId 
         * @param {HomeworkEditRequest} homeworkEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editHomework(homeworkId: number, homeworkEditRequest: HomeworkEditRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseVoid> {
            return localVarFp.editHomework(homeworkId, homeworkEditRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} missionId 
         * @param {HomeworkSubmissionRequest} homeworkSubmissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitHomework(missionId: number, homeworkSubmissionRequest: HomeworkSubmissionRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseHomeworkSubmissionResponse> {
            return localVarFp.submitHomework(missionId, homeworkSubmissionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GroupStudyHomeworkApi - object-oriented interface
 */
export class GroupStudyHomeworkApi extends BaseAPI {
    /**
     * 
     * @param {number} homeworkId 
     * @param {HomeworkEditRequest} homeworkEditRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public editHomework(homeworkId: number, homeworkEditRequest: HomeworkEditRequest, options?: RawAxiosRequestConfig) {
        return GroupStudyHomeworkApiFp(this.configuration).editHomework(homeworkId, homeworkEditRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} missionId 
     * @param {HomeworkSubmissionRequest} homeworkSubmissionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitHomework(missionId: number, homeworkSubmissionRequest: HomeworkSubmissionRequest, options?: RawAxiosRequestConfig) {
        return GroupStudyHomeworkApiFp(this.configuration).submitHomework(missionId, homeworkSubmissionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

