/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseString } from '../models';
/**
 * GrowthHallOfFameAdminApi - axios parameter creator
 */
export const GrowthHallOfFameAdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 지정된 날짜 기준으로 일간 랭킹 배치를 실행합니다. (date 미지정 시 오늘 기준으로 어제 데이터 집계)
         * @summary 일간 랭킹 배치 수동 실행
         * @param {string} [date] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runDailyRankingBatch: async (date?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/hall-of-fame/batch/daily-ranking`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (date !== undefined) {
                localVarQueryParameter['date'] = (date as any instanceof Date) ?
                    (date as any).toISOString().substring(0,10) :
                    date;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 주차 시작일(월요일)을 직접 지정하여 MVP 배치를 실행합니다. weeklyPeriodIdentifier 미지정 시 최근 마감 주차(금요일 23:59 마감)의 월요일을 기준으로 실행합니다.
         * @summary 주간 MVP 배치 수동 실행
         * @param {string} [weeklyPeriodIdentifier] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runWeeklyMVPBatch: async (weeklyPeriodIdentifier?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admin/hall-of-fame/batch/weekly-mvp`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (weeklyPeriodIdentifier !== undefined) {
                localVarQueryParameter['weeklyPeriodIdentifier'] = (weeklyPeriodIdentifier as any instanceof Date) ?
                    (weeklyPeriodIdentifier as any).toISOString().substring(0,10) :
                    weeklyPeriodIdentifier;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GrowthHallOfFameAdminApi - functional programming interface
 */
export const GrowthHallOfFameAdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GrowthHallOfFameAdminApiAxiosParamCreator(configuration)
    return {
        /**
         * 지정된 날짜 기준으로 일간 랭킹 배치를 실행합니다. (date 미지정 시 오늘 기준으로 어제 데이터 집계)
         * @summary 일간 랭킹 배치 수동 실행
         * @param {string} [date] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runDailyRankingBatch(date?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runDailyRankingBatch(date, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GrowthHallOfFameAdminApi.runDailyRankingBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 주차 시작일(월요일)을 직접 지정하여 MVP 배치를 실행합니다. weeklyPeriodIdentifier 미지정 시 최근 마감 주차(금요일 23:59 마감)의 월요일을 기준으로 실행합니다.
         * @summary 주간 MVP 배치 수동 실행
         * @param {string} [weeklyPeriodIdentifier] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runWeeklyMVPBatch(weeklyPeriodIdentifier?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runWeeklyMVPBatch(weeklyPeriodIdentifier, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GrowthHallOfFameAdminApi.runWeeklyMVPBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GrowthHallOfFameAdminApi - factory interface
 */
export const GrowthHallOfFameAdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GrowthHallOfFameAdminApiFp(configuration)
    return {
        /**
         * 지정된 날짜 기준으로 일간 랭킹 배치를 실행합니다. (date 미지정 시 오늘 기준으로 어제 데이터 집계)
         * @summary 일간 랭킹 배치 수동 실행
         * @param {string} [date] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runDailyRankingBatch(date?: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseString> {
            return localVarFp.runDailyRankingBatch(date, options).then((request) => request(axios, basePath));
        },
        /**
         * 주차 시작일(월요일)을 직접 지정하여 MVP 배치를 실행합니다. weeklyPeriodIdentifier 미지정 시 최근 마감 주차(금요일 23:59 마감)의 월요일을 기준으로 실행합니다.
         * @summary 주간 MVP 배치 수동 실행
         * @param {string} [weeklyPeriodIdentifier] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runWeeklyMVPBatch(weeklyPeriodIdentifier?: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseString> {
            return localVarFp.runWeeklyMVPBatch(weeklyPeriodIdentifier, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GrowthHallOfFameAdminApi - object-oriented interface
 */
export class GrowthHallOfFameAdminApi extends BaseAPI {
    /**
     * 지정된 날짜 기준으로 일간 랭킹 배치를 실행합니다. (date 미지정 시 오늘 기준으로 어제 데이터 집계)
     * @summary 일간 랭킹 배치 수동 실행
     * @param {string} [date] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runDailyRankingBatch(date?: string, options?: RawAxiosRequestConfig) {
        return GrowthHallOfFameAdminApiFp(this.configuration).runDailyRankingBatch(date, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 주차 시작일(월요일)을 직접 지정하여 MVP 배치를 실행합니다. weeklyPeriodIdentifier 미지정 시 최근 마감 주차(금요일 23:59 마감)의 월요일을 기준으로 실행합니다.
     * @summary 주간 MVP 배치 수동 실행
     * @param {string} [weeklyPeriodIdentifier] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runWeeklyMVPBatch(weeklyPeriodIdentifier?: string, options?: RawAxiosRequestConfig) {
        return GrowthHallOfFameAdminApiFp(this.configuration).runWeeklyMVPBatch(weeklyPeriodIdentifier, options).then((request) => request(this.axios, this.basePath));
    }
}

