/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LessonQnaAnswerReactionRequest } from '../models';
/**
 * LessonQnaAnswerControllerApi - axios parameter creator
 */
export const LessonQnaAnswerControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *                 FRD D-11.                  답변의 도움돼요 / 도움안돼요 반응을 토글합니다.                  답변 반응은 개별 답변의 유용성을 빠르게 드러내는 경량 상호작용입니다. 토글 후 카운트를 즉시 반영할 수 있도록 응답이 단순해야 합니다.  ## Narrative - 이 API는 답변마다 도움돼요 또는 도움안돼요를 표시할 때 호출합니다.   - 질문 상세 안에서도 개별 답변 품질을 빠르게 드러내기 위한 경량 상호작용입니다.   - 동작 방식은 질문 반응과 비슷하지만, 카운트 대상이 답변 row라는 점이 다릅니다. - 로그인 사용자만 사용할 수 있습니다.   - 비로그인은 읽기만 가능하고, 반응은 남길 수 없습니다.   - 같은 reactionType을 다시 누르면 취소되는 토글입니다. - 프론트엔드는 해당 answer row만 정확히 갱신하면 됩니다.   - isActive, helpfulCount, notHelpfulCount를 응답값으로 바로 바꾸면 됩니다.   - 다른 답변 row까지 건드릴 필요는 없지만, 상세 전체 상태와 모순이 나지 않게 서버 결과를 우선해야 합니다.  ## Screen Preview - 이미지명: S-질문상세   - 이미지 설명: 질문 상세와 답변 목록, 반응 버튼, 수정·삭제 메뉴가 함께 보이는 화면입니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v0.6/S-질문상세.png`   - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png`    <img src=\"/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png\" alt=\"S-질문상세\" width=\"720\" />  ## Screen Usage | 비고 | 설명 | |---|---| | Primary Screen | S-질문상세 | | reactionType | 사용자가 누른 버튼(HELPFUL/NOT_HELPFUL) source입니다. | | isActive | 버튼 active/inactive 상태 source입니다. | | helpfulCount / notHelpfulCount | 답변 반응 카운터 즉시 갱신 source입니다. |  ## Access | 항목 | 설명 | |---|---| | 권한 | 로그인 사용자만 반응을 남길 수 있습니다. |  ## Response Fields | 필드 | 설명 | |---|---| | isActive | 현재 사용자의 반응 활성화 상태입니다. | | helpfulCount / notHelpfulCount | 토글 후 최종 카운트입니다. |  ## Rules | 항목 | 설명 | |---|---| | 규칙 | 같은 reactionType을 다시 누르면 취소됩니다. |  
         * @summary 답변 반응 토글
         * @param {number} answerId 
         * @param {LessonQnaAnswerReactionRequest} lessonQnaAnswerReactionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleReaction1: async (answerId: number, lessonQnaAnswerReactionRequest: LessonQnaAnswerReactionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'answerId' is not null or undefined
            assertParamExists('toggleReaction1', 'answerId', answerId)
            // verify required parameter 'lessonQnaAnswerReactionRequest' is not null or undefined
            assertParamExists('toggleReaction1', 'lessonQnaAnswerReactionRequest', lessonQnaAnswerReactionRequest)
            const localVarPath = `/api/v5/qna-answers/{answerId}/reactions`
                .replace(`{${"answerId"}}`, encodeURIComponent(String(answerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(lessonQnaAnswerReactionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LessonQnaAnswerControllerApi - functional programming interface
 */
export const LessonQnaAnswerControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LessonQnaAnswerControllerApiAxiosParamCreator(configuration)
    return {
        /**
         *                 FRD D-11.                  답변의 도움돼요 / 도움안돼요 반응을 토글합니다.                  답변 반응은 개별 답변의 유용성을 빠르게 드러내는 경량 상호작용입니다. 토글 후 카운트를 즉시 반영할 수 있도록 응답이 단순해야 합니다.  ## Narrative - 이 API는 답변마다 도움돼요 또는 도움안돼요를 표시할 때 호출합니다.   - 질문 상세 안에서도 개별 답변 품질을 빠르게 드러내기 위한 경량 상호작용입니다.   - 동작 방식은 질문 반응과 비슷하지만, 카운트 대상이 답변 row라는 점이 다릅니다. - 로그인 사용자만 사용할 수 있습니다.   - 비로그인은 읽기만 가능하고, 반응은 남길 수 없습니다.   - 같은 reactionType을 다시 누르면 취소되는 토글입니다. - 프론트엔드는 해당 answer row만 정확히 갱신하면 됩니다.   - isActive, helpfulCount, notHelpfulCount를 응답값으로 바로 바꾸면 됩니다.   - 다른 답변 row까지 건드릴 필요는 없지만, 상세 전체 상태와 모순이 나지 않게 서버 결과를 우선해야 합니다.  ## Screen Preview - 이미지명: S-질문상세   - 이미지 설명: 질문 상세와 답변 목록, 반응 버튼, 수정·삭제 메뉴가 함께 보이는 화면입니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v0.6/S-질문상세.png`   - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png`    <img src=\"/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png\" alt=\"S-질문상세\" width=\"720\" />  ## Screen Usage | 비고 | 설명 | |---|---| | Primary Screen | S-질문상세 | | reactionType | 사용자가 누른 버튼(HELPFUL/NOT_HELPFUL) source입니다. | | isActive | 버튼 active/inactive 상태 source입니다. | | helpfulCount / notHelpfulCount | 답변 반응 카운터 즉시 갱신 source입니다. |  ## Access | 항목 | 설명 | |---|---| | 권한 | 로그인 사용자만 반응을 남길 수 있습니다. |  ## Response Fields | 필드 | 설명 | |---|---| | isActive | 현재 사용자의 반응 활성화 상태입니다. | | helpfulCount / notHelpfulCount | 토글 후 최종 카운트입니다. |  ## Rules | 항목 | 설명 | |---|---| | 규칙 | 같은 reactionType을 다시 누르면 취소됩니다. |  
         * @summary 답변 반응 토글
         * @param {number} answerId 
         * @param {LessonQnaAnswerReactionRequest} lessonQnaAnswerReactionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async toggleReaction1(answerId: number, lessonQnaAnswerReactionRequest: LessonQnaAnswerReactionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.toggleReaction1(answerId, lessonQnaAnswerReactionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LessonQnaAnswerControllerApi.toggleReaction1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LessonQnaAnswerControllerApi - factory interface
 */
export const LessonQnaAnswerControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LessonQnaAnswerControllerApiFp(configuration)
    return {
        /**
         *                 FRD D-11.                  답변의 도움돼요 / 도움안돼요 반응을 토글합니다.                  답변 반응은 개별 답변의 유용성을 빠르게 드러내는 경량 상호작용입니다. 토글 후 카운트를 즉시 반영할 수 있도록 응답이 단순해야 합니다.  ## Narrative - 이 API는 답변마다 도움돼요 또는 도움안돼요를 표시할 때 호출합니다.   - 질문 상세 안에서도 개별 답변 품질을 빠르게 드러내기 위한 경량 상호작용입니다.   - 동작 방식은 질문 반응과 비슷하지만, 카운트 대상이 답변 row라는 점이 다릅니다. - 로그인 사용자만 사용할 수 있습니다.   - 비로그인은 읽기만 가능하고, 반응은 남길 수 없습니다.   - 같은 reactionType을 다시 누르면 취소되는 토글입니다. - 프론트엔드는 해당 answer row만 정확히 갱신하면 됩니다.   - isActive, helpfulCount, notHelpfulCount를 응답값으로 바로 바꾸면 됩니다.   - 다른 답변 row까지 건드릴 필요는 없지만, 상세 전체 상태와 모순이 나지 않게 서버 결과를 우선해야 합니다.  ## Screen Preview - 이미지명: S-질문상세   - 이미지 설명: 질문 상세와 답변 목록, 반응 버튼, 수정·삭제 메뉴가 함께 보이는 화면입니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v0.6/S-질문상세.png`   - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png`    <img src=\"/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png\" alt=\"S-질문상세\" width=\"720\" />  ## Screen Usage | 비고 | 설명 | |---|---| | Primary Screen | S-질문상세 | | reactionType | 사용자가 누른 버튼(HELPFUL/NOT_HELPFUL) source입니다. | | isActive | 버튼 active/inactive 상태 source입니다. | | helpfulCount / notHelpfulCount | 답변 반응 카운터 즉시 갱신 source입니다. |  ## Access | 항목 | 설명 | |---|---| | 권한 | 로그인 사용자만 반응을 남길 수 있습니다. |  ## Response Fields | 필드 | 설명 | |---|---| | isActive | 현재 사용자의 반응 활성화 상태입니다. | | helpfulCount / notHelpfulCount | 토글 후 최종 카운트입니다. |  ## Rules | 항목 | 설명 | |---|---| | 규칙 | 같은 reactionType을 다시 누르면 취소됩니다. |  
         * @summary 답변 반응 토글
         * @param {number} answerId 
         * @param {LessonQnaAnswerReactionRequest} lessonQnaAnswerReactionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleReaction1(answerId: number, lessonQnaAnswerReactionRequest: LessonQnaAnswerReactionRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.toggleReaction1(answerId, lessonQnaAnswerReactionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LessonQnaAnswerControllerApi - object-oriented interface
 */
export class LessonQnaAnswerControllerApi extends BaseAPI {
    /**
     *                 FRD D-11.                  답변의 도움돼요 / 도움안돼요 반응을 토글합니다.                  답변 반응은 개별 답변의 유용성을 빠르게 드러내는 경량 상호작용입니다. 토글 후 카운트를 즉시 반영할 수 있도록 응답이 단순해야 합니다.  ## Narrative - 이 API는 답변마다 도움돼요 또는 도움안돼요를 표시할 때 호출합니다.   - 질문 상세 안에서도 개별 답변 품질을 빠르게 드러내기 위한 경량 상호작용입니다.   - 동작 방식은 질문 반응과 비슷하지만, 카운트 대상이 답변 row라는 점이 다릅니다. - 로그인 사용자만 사용할 수 있습니다.   - 비로그인은 읽기만 가능하고, 반응은 남길 수 없습니다.   - 같은 reactionType을 다시 누르면 취소되는 토글입니다. - 프론트엔드는 해당 answer row만 정확히 갱신하면 됩니다.   - isActive, helpfulCount, notHelpfulCount를 응답값으로 바로 바꾸면 됩니다.   - 다른 답변 row까지 건드릴 필요는 없지만, 상세 전체 상태와 모순이 나지 않게 서버 결과를 우선해야 합니다.  ## Screen Preview - 이미지명: S-질문상세   - 이미지 설명: 질문 상세와 답변 목록, 반응 버튼, 수정·삭제 메뉴가 함께 보이는 화면입니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v0.6/S-질문상세.png`   - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png`    <img src=\"/api-docs/frd-screenmap/v0.6/S-%EC%A7%88%EB%AC%B8%EC%83%81%EC%84%B8.png\" alt=\"S-질문상세\" width=\"720\" />  ## Screen Usage | 비고 | 설명 | |---|---| | Primary Screen | S-질문상세 | | reactionType | 사용자가 누른 버튼(HELPFUL/NOT_HELPFUL) source입니다. | | isActive | 버튼 active/inactive 상태 source입니다. | | helpfulCount / notHelpfulCount | 답변 반응 카운터 즉시 갱신 source입니다. |  ## Access | 항목 | 설명 | |---|---| | 권한 | 로그인 사용자만 반응을 남길 수 있습니다. |  ## Response Fields | 필드 | 설명 | |---|---| | isActive | 현재 사용자의 반응 활성화 상태입니다. | | helpfulCount / notHelpfulCount | 토글 후 최종 카운트입니다. |  ## Rules | 항목 | 설명 | |---|---| | 규칙 | 같은 reactionType을 다시 누르면 취소됩니다. |  
     * @summary 답변 반응 토글
     * @param {number} answerId 
     * @param {LessonQnaAnswerReactionRequest} lessonQnaAnswerReactionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public toggleReaction1(answerId: number, lessonQnaAnswerReactionRequest: LessonQnaAnswerReactionRequest, options?: RawAxiosRequestConfig) {
        return LessonQnaAnswerControllerApiFp(this.configuration).toggleReaction1(answerId, lessonQnaAnswerReactionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

