/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { MatchingSystemStatusSchema } from '../models';
// @ts-ignore
import type { RequestAutoStudyMatchingDto } from '../models';
/**
 * MatchingApi - axios parameter creator
 */
export const MatchingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 사용자가 CS 스터디 매칭을 위해 정보를 입력하고 신청합니다. 요청 본문에는 멤버id, 자기소개, 스터디 계획, 선호 주제, 가능 시간대, 기술 스택, 연락처, GitHub/SNS URL 등이 포함됩니다.
         * @summary CS 스터디 매칭 신청
         * @param {RequestAutoStudyMatchingDto} requestAutoStudyMatchingDto CS 스터디 매칭 신청 화면에서 매칭 신청 확인 버튼을 누를때 사용할 Api입니다.  CS 스터디 매칭 신청 화면을 불러올때는 테크스택 id 리스트 조회와 가능 시간대 id 리스트 조회가 필요합니다.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applyForStudyMatching: async (requestAutoStudyMatchingDto: RequestAutoStudyMatchingDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestAutoStudyMatchingDto' is not null or undefined
            assertParamExists('applyForStudyMatching', 'requestAutoStudyMatchingDto', requestAutoStudyMatchingDto)
            const localVarPath = `/api/v1/matching/apply`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestAutoStudyMatchingDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 매칭 시스템의 상태를 조회합니다. (RECRUITING: 모집중, STUDYING: 스터디 진행중)
         * @summary 매칭 시스템 현재 상태 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchingSystemStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/matching/system-status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MatchingApi - functional programming interface
 */
export const MatchingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MatchingApiAxiosParamCreator(configuration)
    return {
        /**
         * 사용자가 CS 스터디 매칭을 위해 정보를 입력하고 신청합니다. 요청 본문에는 멤버id, 자기소개, 스터디 계획, 선호 주제, 가능 시간대, 기술 스택, 연락처, GitHub/SNS URL 등이 포함됩니다.
         * @summary CS 스터디 매칭 신청
         * @param {RequestAutoStudyMatchingDto} requestAutoStudyMatchingDto CS 스터디 매칭 신청 화면에서 매칭 신청 확인 버튼을 누를때 사용할 Api입니다.  CS 스터디 매칭 신청 화면을 불러올때는 테크스택 id 리스트 조회와 가능 시간대 id 리스트 조회가 필요합니다.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async applyForStudyMatching(requestAutoStudyMatchingDto: RequestAutoStudyMatchingDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.applyForStudyMatching(requestAutoStudyMatchingDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MatchingApi.applyForStudyMatching']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 매칭 시스템의 상태를 조회합니다. (RECRUITING: 모집중, STUDYING: 스터디 진행중)
         * @summary 매칭 시스템 현재 상태 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMatchingSystemStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MatchingSystemStatusSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMatchingSystemStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MatchingApi.getMatchingSystemStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MatchingApi - factory interface
 */
export const MatchingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MatchingApiFp(configuration)
    return {
        /**
         * 사용자가 CS 스터디 매칭을 위해 정보를 입력하고 신청합니다. 요청 본문에는 멤버id, 자기소개, 스터디 계획, 선호 주제, 가능 시간대, 기술 스택, 연락처, GitHub/SNS URL 등이 포함됩니다.
         * @summary CS 스터디 매칭 신청
         * @param {RequestAutoStudyMatchingDto} requestAutoStudyMatchingDto CS 스터디 매칭 신청 화면에서 매칭 신청 확인 버튼을 누를때 사용할 Api입니다.  CS 스터디 매칭 신청 화면을 불러올때는 테크스택 id 리스트 조회와 가능 시간대 id 리스트 조회가 필요합니다.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applyForStudyMatching(requestAutoStudyMatchingDto: RequestAutoStudyMatchingDto, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.applyForStudyMatching(requestAutoStudyMatchingDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 매칭 시스템의 상태를 조회합니다. (RECRUITING: 모집중, STUDYING: 스터디 진행중)
         * @summary 매칭 시스템 현재 상태 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchingSystemStatus(options?: RawAxiosRequestConfig): AxiosPromise<MatchingSystemStatusSchema> {
            return localVarFp.getMatchingSystemStatus(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MatchingApi - object-oriented interface
 */
export class MatchingApi extends BaseAPI {
    /**
     * 사용자가 CS 스터디 매칭을 위해 정보를 입력하고 신청합니다. 요청 본문에는 멤버id, 자기소개, 스터디 계획, 선호 주제, 가능 시간대, 기술 스택, 연락처, GitHub/SNS URL 등이 포함됩니다.
     * @summary CS 스터디 매칭 신청
     * @param {RequestAutoStudyMatchingDto} requestAutoStudyMatchingDto CS 스터디 매칭 신청 화면에서 매칭 신청 확인 버튼을 누를때 사용할 Api입니다.  CS 스터디 매칭 신청 화면을 불러올때는 테크스택 id 리스트 조회와 가능 시간대 id 리스트 조회가 필요합니다.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public applyForStudyMatching(requestAutoStudyMatchingDto: RequestAutoStudyMatchingDto, options?: RawAxiosRequestConfig) {
        return MatchingApiFp(this.configuration).applyForStudyMatching(requestAutoStudyMatchingDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 매칭 시스템의 상태를 조회합니다. (RECRUITING: 모집중, STUDYING: 스터디 진행중)
     * @summary 매칭 시스템 현재 상태 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMatchingSystemStatus(options?: RawAxiosRequestConfig) {
        return MatchingApiFp(this.configuration).getMatchingSystemStatus(options).then((request) => request(this.axios, this.basePath));
    }
}

