/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { MyClassWithdrawalRequest } from '../models';
// @ts-ignore
import type { MyClassWithdrawalResponse } from '../models';
/**
 * MyClassWithdrawalApi - axios parameter creator
 */
export const MyClassWithdrawalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * FRD B-21.  `S-클래스탈퇴`의 최종 탈퇴 CTA를 처리하고 class withdrawal audit를 저장합니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v1.0/S-클래스탈퇴.png` - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png`  <img src=\"/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png\" alt=\"S-클래스탈퇴\" width=\"720\" /> 
         * @summary 클래스 탈퇴
         * @param {MyClassWithdrawalRequest} myClassWithdrawalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        withdraw: async (myClassWithdrawalRequest: MyClassWithdrawalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'myClassWithdrawalRequest' is not null or undefined
            assertParamExists('withdraw', 'myClassWithdrawalRequest', myClassWithdrawalRequest)
            const localVarPath = `/api/v6/mypage/class/withdraw`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(myClassWithdrawalRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MyClassWithdrawalApi - functional programming interface
 */
export const MyClassWithdrawalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MyClassWithdrawalApiAxiosParamCreator(configuration)
    return {
        /**
         * FRD B-21.  `S-클래스탈퇴`의 최종 탈퇴 CTA를 처리하고 class withdrawal audit를 저장합니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v1.0/S-클래스탈퇴.png` - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png`  <img src=\"/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png\" alt=\"S-클래스탈퇴\" width=\"720\" /> 
         * @summary 클래스 탈퇴
         * @param {MyClassWithdrawalRequest} myClassWithdrawalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async withdraw(myClassWithdrawalRequest: MyClassWithdrawalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MyClassWithdrawalResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.withdraw(myClassWithdrawalRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MyClassWithdrawalApi.withdraw']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MyClassWithdrawalApi - factory interface
 */
export const MyClassWithdrawalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MyClassWithdrawalApiFp(configuration)
    return {
        /**
         * FRD B-21.  `S-클래스탈퇴`의 최종 탈퇴 CTA를 처리하고 class withdrawal audit를 저장합니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v1.0/S-클래스탈퇴.png` - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png`  <img src=\"/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png\" alt=\"S-클래스탈퇴\" width=\"720\" /> 
         * @summary 클래스 탈퇴
         * @param {MyClassWithdrawalRequest} myClassWithdrawalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        withdraw(myClassWithdrawalRequest: MyClassWithdrawalRequest, options?: RawAxiosRequestConfig): AxiosPromise<MyClassWithdrawalResponse> {
            return localVarFp.withdraw(myClassWithdrawalRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MyClassWithdrawalApi - object-oriented interface
 */
export class MyClassWithdrawalApi extends BaseAPI {
    /**
     * FRD B-21.  `S-클래스탈퇴`의 최종 탈퇴 CTA를 처리하고 class withdrawal audit를 저장합니다.  - Screenmap Path: `src/main/resources/static/api-docs/frd-screenmap/v1.0/S-클래스탈퇴.png` - Screenmap Raw URL: `https://raw.githubusercontent.com/code-zero-to-one/study-platform-mvp/dev/src/main/resources/static/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png`  <img src=\"/api-docs/frd-screenmap/v1.0/S-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%83%88%ED%87%B4.png\" alt=\"S-클래스탈퇴\" width=\"720\" /> 
     * @summary 클래스 탈퇴
     * @param {MyClassWithdrawalRequest} myClassWithdrawalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public withdraw(myClassWithdrawalRequest: MyClassWithdrawalRequest, options?: RawAxiosRequestConfig) {
        return MyClassWithdrawalApiFp(this.configuration).withdraw(myClassWithdrawalRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

