/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PhoneAuthResponseSchema } from '../models';
// @ts-ignore
import type { PhoneAuthSendRequestDto } from '../models';
// @ts-ignore
import type { PhoneAuthVerifyRequestDto } from '../models';
/**
 * PhoneAuthApi - axios parameter creator
 */
export const PhoneAuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 입력된 전화번호로 6자리 인증번호를 발송합니다.  - 인증번호는 3분간 유효하며, 캐시에 저장됩니다.  - 개발/테스트 환경에서는 실제 SMS 발송 대신 로그로 출력됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"인증번호가 발송되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 발송 성공\" | 
         * @summary SMS 인증번호 발송
         * @param {PhoneAuthSendRequestDto} phoneAuthSendRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendVerificationCode: async (phoneAuthSendRequestDto: PhoneAuthSendRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'phoneAuthSendRequestDto' is not null or undefined
            assertParamExists('sendVerificationCode', 'phoneAuthSendRequestDto', phoneAuthSendRequestDto)
            const localVarPath = `/api/v1/auth/phone/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(phoneAuthSendRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 발송된 인증번호를 검증하고 회원 정보를 업데이트합니다.  - 검증 성공 시 회원의 실명, 전화번호가 저장되고 인증 상태가 완료로 변경됩니다.  - 이미 다른 계정에 등록된 전화번호로 인증을 시도하여 성공할 경우 (**전화번호**를 기준으로 동일 인물 여부를 판단합니다):   - 기존 계정: **실명 정보는 유지**되지만, **본인인증 상태가 해제**되고 **전화번호 정보가 삭제**됩니다.   - 현재 계정: 해당 전화번호로 **본인인증이 활성화**됩니다.  - 인증번호는 검증 후 캐시에서 자동으로 삭제됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" | | code | string | 인증번호 (6자리 숫자) | 필수 | \"152943\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 404: 회원 없음 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"본인인증이 완료되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 검증 성공\" | 
         * @summary SMS 인증번호 검증
         * @param {PhoneAuthVerifyRequestDto} phoneAuthVerifyRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyCode: async (phoneAuthVerifyRequestDto: PhoneAuthVerifyRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'phoneAuthVerifyRequestDto' is not null or undefined
            assertParamExists('verifyCode', 'phoneAuthVerifyRequestDto', phoneAuthVerifyRequestDto)
            const localVarPath = `/api/v1/auth/phone/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(phoneAuthVerifyRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PhoneAuthApi - functional programming interface
 */
export const PhoneAuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PhoneAuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 입력된 전화번호로 6자리 인증번호를 발송합니다.  - 인증번호는 3분간 유효하며, 캐시에 저장됩니다.  - 개발/테스트 환경에서는 실제 SMS 발송 대신 로그로 출력됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"인증번호가 발송되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 발송 성공\" | 
         * @summary SMS 인증번호 발송
         * @param {PhoneAuthSendRequestDto} phoneAuthSendRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendVerificationCode(phoneAuthSendRequestDto: PhoneAuthSendRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PhoneAuthResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendVerificationCode(phoneAuthSendRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PhoneAuthApi.sendVerificationCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 발송된 인증번호를 검증하고 회원 정보를 업데이트합니다.  - 검증 성공 시 회원의 실명, 전화번호가 저장되고 인증 상태가 완료로 변경됩니다.  - 이미 다른 계정에 등록된 전화번호로 인증을 시도하여 성공할 경우 (**전화번호**를 기준으로 동일 인물 여부를 판단합니다):   - 기존 계정: **실명 정보는 유지**되지만, **본인인증 상태가 해제**되고 **전화번호 정보가 삭제**됩니다.   - 현재 계정: 해당 전화번호로 **본인인증이 활성화**됩니다.  - 인증번호는 검증 후 캐시에서 자동으로 삭제됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" | | code | string | 인증번호 (6자리 숫자) | 필수 | \"152943\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 404: 회원 없음 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"본인인증이 완료되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 검증 성공\" | 
         * @summary SMS 인증번호 검증
         * @param {PhoneAuthVerifyRequestDto} phoneAuthVerifyRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyCode(phoneAuthVerifyRequestDto: PhoneAuthVerifyRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PhoneAuthResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyCode(phoneAuthVerifyRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PhoneAuthApi.verifyCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PhoneAuthApi - factory interface
 */
export const PhoneAuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PhoneAuthApiFp(configuration)
    return {
        /**
         * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 입력된 전화번호로 6자리 인증번호를 발송합니다.  - 인증번호는 3분간 유효하며, 캐시에 저장됩니다.  - 개발/테스트 환경에서는 실제 SMS 발송 대신 로그로 출력됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"인증번호가 발송되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 발송 성공\" | 
         * @summary SMS 인증번호 발송
         * @param {PhoneAuthSendRequestDto} phoneAuthSendRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendVerificationCode(phoneAuthSendRequestDto: PhoneAuthSendRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<PhoneAuthResponseSchema> {
            return localVarFp.sendVerificationCode(phoneAuthSendRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 발송된 인증번호를 검증하고 회원 정보를 업데이트합니다.  - 검증 성공 시 회원의 실명, 전화번호가 저장되고 인증 상태가 완료로 변경됩니다.  - 이미 다른 계정에 등록된 전화번호로 인증을 시도하여 성공할 경우 (**전화번호**를 기준으로 동일 인물 여부를 판단합니다):   - 기존 계정: **실명 정보는 유지**되지만, **본인인증 상태가 해제**되고 **전화번호 정보가 삭제**됩니다.   - 현재 계정: 해당 전화번호로 **본인인증이 활성화**됩니다.  - 인증번호는 검증 후 캐시에서 자동으로 삭제됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" | | code | string | 인증번호 (6자리 숫자) | 필수 | \"152943\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 404: 회원 없음 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"본인인증이 완료되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 검증 성공\" | 
         * @summary SMS 인증번호 검증
         * @param {PhoneAuthVerifyRequestDto} phoneAuthVerifyRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyCode(phoneAuthVerifyRequestDto: PhoneAuthVerifyRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<PhoneAuthResponseSchema> {
            return localVarFp.verifyCode(phoneAuthVerifyRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PhoneAuthApi - object-oriented interface
 */
export class PhoneAuthApi extends BaseAPI {
    /**
     * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 입력된 전화번호로 6자리 인증번호를 발송합니다.  - 인증번호는 3분간 유효하며, 캐시에 저장됩니다.  - 개발/테스트 환경에서는 실제 SMS 발송 대신 로그로 출력됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"인증번호가 발송되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 발송 성공\" | 
     * @summary SMS 인증번호 발송
     * @param {PhoneAuthSendRequestDto} phoneAuthSendRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendVerificationCode(phoneAuthSendRequestDto: PhoneAuthSendRequestDto, options?: RawAxiosRequestConfig) {
        return PhoneAuthApiFp(this.configuration).sendVerificationCode(phoneAuthSendRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 작성일자: 2025-12-11  작성자: 최현준  ---  ## Description  - 발송된 인증번호를 검증하고 회원 정보를 업데이트합니다.  - 검증 성공 시 회원의 실명, 전화번호가 저장되고 인증 상태가 완료로 변경됩니다.  - 이미 다른 계정에 등록된 전화번호로 인증을 시도하여 성공할 경우 (**전화번호**를 기준으로 동일 인물 여부를 판단합니다):   - 기존 계정: **실명 정보는 유지**되지만, **본인인증 상태가 해제**되고 **전화번호 정보가 삭제**됩니다.   - 현재 계정: 해당 전화번호로 **본인인증이 활성화**됩니다.  - 인증번호는 검증 후 캐시에서 자동으로 삭제됩니다.  ---  ## Request  | **키** | **타입** | **설명** | **필수 여부** | **예시** | | --- | --- | --- | --- | --- | | realName | string | 실명 | 필수 | \"홍길동\" | | phoneNumber | string | 전화번호 (01로 시작하는 10-11자리) | 필수 | \"01012345678\" | | code | string | 인증번호 (6자리 숫자) | 필수 | \"152943\" |  ---  ## Response  | **키** | **타입** | **설명** | **예시** | | --- | --- | --- | --- | | statusCode | number | 상태 코드 | 200: 성공 / 400: 클라이언트 요청 오류 / 401: 인증 실패 / 404: 회원 없음 / 500: 그 외 | | timestamp | string(datetime) | 응답 일시 | \"2025-12-11T10:11:12.123456\" | | content | object | 응답 데이터 | - | | content.success | boolean | 성공 여부 | true | | content.message | string | 처리 결과 메시지 | \"본인인증이 완료되었습니다.\" | | message | string | 처리 결과 | \"SMS 인증번호 검증 성공\" | 
     * @summary SMS 인증번호 검증
     * @param {PhoneAuthVerifyRequestDto} phoneAuthVerifyRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public verifyCode(phoneAuthVerifyRequestDto: PhoneAuthVerifyRequestDto, options?: RawAxiosRequestConfig) {
        return PhoneAuthApiFp(this.configuration).verifyCode(phoneAuthVerifyRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

