/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponsePageResponseDtoStudyRefundSummaryResponse } from '../models';
// @ts-ignore
import type { BaseResponseStudyRefundDetailResponse } from '../models';
// @ts-ignore
import type { BaseResponseVoid } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
// @ts-ignore
import type { StudyRefundCreateRequest } from '../models';
/**
 * RefundUserApi - axios parameter creator
 */
export const RefundUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} refundId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelRefundRequest: async (refundId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refundId' is not null or undefined
            assertParamExists('cancelRefundRequest', 'refundId', refundId)
            const localVarPath = `/api/v1/refunds/{refundId}/cancel`
                .replace(`{${"refundId"}}`, encodeURIComponent(String(refundId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyRefunds: async (pageable: Pageable, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getMyRefunds', 'pageable', pageable)
            const localVarPath = `/api/v1/mypage/refunds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} paymentId 
         * @param {StudyRefundCreateRequest} studyRefundCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRefund: async (paymentId: number, studyRefundCreateRequest: StudyRefundCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentId' is not null or undefined
            assertParamExists('requestRefund', 'paymentId', paymentId)
            // verify required parameter 'studyRefundCreateRequest' is not null or undefined
            assertParamExists('requestRefund', 'studyRefundCreateRequest', studyRefundCreateRequest)
            const localVarPath = `/api/v1/payments/{paymentId}/refunds`
                .replace(`{${"paymentId"}}`, encodeURIComponent(String(paymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(studyRefundCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RefundUserApi - functional programming interface
 */
export const RefundUserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RefundUserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} refundId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelRefundRequest(refundId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelRefundRequest(refundId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RefundUserApi.cancelRefundRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyRefunds(pageable: Pageable, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageResponseDtoStudyRefundSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyRefunds(pageable, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RefundUserApi.getMyRefunds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} paymentId 
         * @param {StudyRefundCreateRequest} studyRefundCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestRefund(paymentId: number, studyRefundCreateRequest: StudyRefundCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseStudyRefundDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestRefund(paymentId, studyRefundCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RefundUserApi.requestRefund']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RefundUserApi - factory interface
 */
export const RefundUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RefundUserApiFp(configuration)
    return {
        /**
         * 
         * @param {number} refundId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelRefundRequest(refundId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseVoid> {
            return localVarFp.cancelRefundRequest(refundId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyRefunds(pageable: Pageable, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageResponseDtoStudyRefundSummaryResponse> {
            return localVarFp.getMyRefunds(pageable, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} paymentId 
         * @param {StudyRefundCreateRequest} studyRefundCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestRefund(paymentId: number, studyRefundCreateRequest: StudyRefundCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseStudyRefundDetailResponse> {
            return localVarFp.requestRefund(paymentId, studyRefundCreateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RefundUserApi - object-oriented interface
 */
export class RefundUserApi extends BaseAPI {
    /**
     * 
     * @param {number} refundId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelRefundRequest(refundId: number, options?: RawAxiosRequestConfig) {
        return RefundUserApiFp(this.configuration).cancelRefundRequest(refundId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Pageable} pageable 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyRefunds(pageable: Pageable, options?: RawAxiosRequestConfig) {
        return RefundUserApiFp(this.configuration).getMyRefunds(pageable, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} paymentId 
     * @param {StudyRefundCreateRequest} studyRefundCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public requestRefund(paymentId: number, studyRefundCreateRequest: StudyRefundCreateRequest, options?: RawAxiosRequestConfig) {
        return RefundUserApiFp(this.configuration).requestRefund(paymentId, studyRefundCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

