/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { RegisterReviewRequest } from '../models';
/**
 * StudyReviewApi - axios parameter creator
 */
export const StudyReviewApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 자신의 스터디 후기 목록을 조회합니다.  - 페이로드에 cursor 값이 없는 경우(첫 페이지): 사용자가 받은 총 후기 개수 반환 O  - 페이로드에 cursor 값이 있는 경우(더 보기): 사용자가 받은 총 후기 개수 반환 X
         * @summary 자신의 스터디 후기 목록 조회
         * @param {number} [cursor] 조회를 시작할 스터디 후기 ID, 전송하지 않는 경우 첫 데이터부터 조회
         * @param {number} [pageSize] 조회할 데이터 개수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyReviews: async (cursor?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/study/reviews/members`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page-size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 자신의 스터디 후기 부정 평가(아쉬웠어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
         * @summary 자신의 스터디 후기 부정 평가키워드 목록 조회
         * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNegativeEvalKeywords: async (pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/study/reviews/members/keywords/negative`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['page-size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 자신 또는 다른 사용자의 스터디 후기 긍정 평가(좋았어요 + 괜찮았어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
         * @summary 자신 또는 다른 사용자의 스터디 후기 긍정 평가 키워드 목록 조회
         * @param {number} [memberId] 조회 대상 회원 ID, 전송하지 않는 경우 자신
         * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPositiveEvalKeywords: async (memberId?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/study/reviews/members/keywords/positive`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (memberId !== undefined) {
                localVarQueryParameter['member-id'] = memberId;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page-size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 시점 기준 후기 작성 대상 스터디 및 전체 평가 키워드 목록을 조회합니다.
         * @summary 후기 작성 대상 스터디 및 전체 평가 키워드 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReviewTargetStudy: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/study/reviews/this-week/target-study`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 시점 기준 자신이 스터디 후기 작성 대상자인지 여부를 조회합니다.
         * @summary 자신이 스터디 후기 작성 대상자인지 여부 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isWriter: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/study/reviews/this-week/is-writer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 스터디 후기를 등록합니다.  후기 글 내용이 없는 경우 content 파라미터를 전송하지 않습니다.  content 파라미터를 전송하는 경우에는 0 < content.length <= 1000 으로 전송해야 합니다.
         * @summary 스터디 후기 등록
         * @param {RegisterReviewRequest} registerReviewRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerReview: async (registerReviewRequest: RegisterReviewRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerReviewRequest' is not null or undefined
            assertParamExists('registerReview', 'registerReviewRequest', registerReviewRequest)
            const localVarPath = `/api/v1/study/reviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerReviewRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StudyReviewApi - functional programming interface
 */
export const StudyReviewApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StudyReviewApiAxiosParamCreator(configuration)
    return {
        /**
         * 자신의 스터디 후기 목록을 조회합니다.  - 페이로드에 cursor 값이 없는 경우(첫 페이지): 사용자가 받은 총 후기 개수 반환 O  - 페이로드에 cursor 값이 있는 경우(더 보기): 사용자가 받은 총 후기 개수 반환 X
         * @summary 자신의 스터디 후기 목록 조회
         * @param {number} [cursor] 조회를 시작할 스터디 후기 ID, 전송하지 않는 경우 첫 데이터부터 조회
         * @param {number} [pageSize] 조회할 데이터 개수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyReviews(cursor?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyReviews(cursor, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudyReviewApi.getMyReviews']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 자신의 스터디 후기 부정 평가(아쉬웠어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
         * @summary 자신의 스터디 후기 부정 평가키워드 목록 조회
         * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNegativeEvalKeywords(pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNegativeEvalKeywords(pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudyReviewApi.getNegativeEvalKeywords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 자신 또는 다른 사용자의 스터디 후기 긍정 평가(좋았어요 + 괜찮았어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
         * @summary 자신 또는 다른 사용자의 스터디 후기 긍정 평가 키워드 목록 조회
         * @param {number} [memberId] 조회 대상 회원 ID, 전송하지 않는 경우 자신
         * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPositiveEvalKeywords(memberId?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPositiveEvalKeywords(memberId, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudyReviewApi.getPositiveEvalKeywords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 시점 기준 후기 작성 대상 스터디 및 전체 평가 키워드 목록을 조회합니다.
         * @summary 후기 작성 대상 스터디 및 전체 평가 키워드 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReviewTargetStudy(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReviewTargetStudy(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudyReviewApi.getReviewTargetStudy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 시점 기준 자신이 스터디 후기 작성 대상자인지 여부를 조회합니다.
         * @summary 자신이 스터디 후기 작성 대상자인지 여부 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async isWriter(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.isWriter(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudyReviewApi.isWriter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 스터디 후기를 등록합니다.  후기 글 내용이 없는 경우 content 파라미터를 전송하지 않습니다.  content 파라미터를 전송하는 경우에는 0 < content.length <= 1000 으로 전송해야 합니다.
         * @summary 스터디 후기 등록
         * @param {RegisterReviewRequest} registerReviewRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerReview(registerReviewRequest: RegisterReviewRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerReview(registerReviewRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StudyReviewApi.registerReview']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StudyReviewApi - factory interface
 */
export const StudyReviewApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StudyReviewApiFp(configuration)
    return {
        /**
         * 자신의 스터디 후기 목록을 조회합니다.  - 페이로드에 cursor 값이 없는 경우(첫 페이지): 사용자가 받은 총 후기 개수 반환 O  - 페이로드에 cursor 값이 있는 경우(더 보기): 사용자가 받은 총 후기 개수 반환 X
         * @summary 자신의 스터디 후기 목록 조회
         * @param {number} [cursor] 조회를 시작할 스터디 후기 ID, 전송하지 않는 경우 첫 데이터부터 조회
         * @param {number} [pageSize] 조회할 데이터 개수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyReviews(cursor?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.getMyReviews(cursor, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 자신의 스터디 후기 부정 평가(아쉬웠어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
         * @summary 자신의 스터디 후기 부정 평가키워드 목록 조회
         * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNegativeEvalKeywords(pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.getNegativeEvalKeywords(pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 자신 또는 다른 사용자의 스터디 후기 긍정 평가(좋았어요 + 괜찮았어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
         * @summary 자신 또는 다른 사용자의 스터디 후기 긍정 평가 키워드 목록 조회
         * @param {number} [memberId] 조회 대상 회원 ID, 전송하지 않는 경우 자신
         * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPositiveEvalKeywords(memberId?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.getPositiveEvalKeywords(memberId, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 시점 기준 후기 작성 대상 스터디 및 전체 평가 키워드 목록을 조회합니다.
         * @summary 후기 작성 대상 스터디 및 전체 평가 키워드 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReviewTargetStudy(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.getReviewTargetStudy(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 시점 기준 자신이 스터디 후기 작성 대상자인지 여부를 조회합니다.
         * @summary 자신이 스터디 후기 작성 대상자인지 여부 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isWriter(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.isWriter(options).then((request) => request(axios, basePath));
        },
        /**
         * 스터디 후기를 등록합니다.  후기 글 내용이 없는 경우 content 파라미터를 전송하지 않습니다.  content 파라미터를 전송하는 경우에는 0 < content.length <= 1000 으로 전송해야 합니다.
         * @summary 스터디 후기 등록
         * @param {RegisterReviewRequest} registerReviewRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerReview(registerReviewRequest: RegisterReviewRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponse> {
            return localVarFp.registerReview(registerReviewRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StudyReviewApi - object-oriented interface
 */
export class StudyReviewApi extends BaseAPI {
    /**
     * 자신의 스터디 후기 목록을 조회합니다.  - 페이로드에 cursor 값이 없는 경우(첫 페이지): 사용자가 받은 총 후기 개수 반환 O  - 페이로드에 cursor 값이 있는 경우(더 보기): 사용자가 받은 총 후기 개수 반환 X
     * @summary 자신의 스터디 후기 목록 조회
     * @param {number} [cursor] 조회를 시작할 스터디 후기 ID, 전송하지 않는 경우 첫 데이터부터 조회
     * @param {number} [pageSize] 조회할 데이터 개수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyReviews(cursor?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return StudyReviewApiFp(this.configuration).getMyReviews(cursor, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 자신의 스터디 후기 부정 평가(아쉬웠어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
     * @summary 자신의 스터디 후기 부정 평가키워드 목록 조회
     * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNegativeEvalKeywords(pageSize?: number, options?: RawAxiosRequestConfig) {
        return StudyReviewApiFp(this.configuration).getNegativeEvalKeywords(pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 자신 또는 다른 사용자의 스터디 후기 긍정 평가(좋았어요 + 괜찮았어요) 키워드 목록을 조회합니다.  - 페이로드에 pageSize 값이 있는 경우(첫 페이지): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 O  - 페이로드에 pageSize 값이 없는 경우(더 보기): 사용자가 받은 총 후기 개수(totalCount) 및 총 평가 사용자 수(reviewerCount) 반환 X
     * @summary 자신 또는 다른 사용자의 스터디 후기 긍정 평가 키워드 목록 조회
     * @param {number} [memberId] 조회 대상 회원 ID, 전송하지 않는 경우 자신
     * @param {number} [pageSize] 조회할 데이터 개수, 전송하지 않는 경우 전체
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPositiveEvalKeywords(memberId?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return StudyReviewApiFp(this.configuration).getPositiveEvalKeywords(memberId, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 시점 기준 후기 작성 대상 스터디 및 전체 평가 키워드 목록을 조회합니다.
     * @summary 후기 작성 대상 스터디 및 전체 평가 키워드 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getReviewTargetStudy(options?: RawAxiosRequestConfig) {
        return StudyReviewApiFp(this.configuration).getReviewTargetStudy(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 시점 기준 자신이 스터디 후기 작성 대상자인지 여부를 조회합니다.
     * @summary 자신이 스터디 후기 작성 대상자인지 여부 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public isWriter(options?: RawAxiosRequestConfig) {
        return StudyReviewApiFp(this.configuration).isWriter(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 스터디 후기를 등록합니다.  후기 글 내용이 없는 경우 content 파라미터를 전송하지 않습니다.  content 파라미터를 전송하는 경우에는 0 < content.length <= 1000 으로 전송해야 합니다.
     * @summary 스터디 후기 등록
     * @param {RegisterReviewRequest} registerReviewRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerReview(registerReviewRequest: RegisterReviewRequest, options?: RawAxiosRequestConfig) {
        return StudyReviewApiFp(this.configuration).registerReview(registerReviewRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

