/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminLessonNotionSyncStatusResponse {
    'lessonId'?: number;
    'linked'?: boolean;
    'notionPageId'?: string;
    'notionPageUrl'?: string;
    'notionLastEditedTime'?: string;
    'lastSyncedAt'?: string;
    'lastSyncedChecksum'?: string;
    'syncStatus'?: AdminLessonNotionSyncStatusResponseSyncStatusEnum;
    'lastErrorCode'?: string;
    'lastErrorMessage'?: string;
    'changedSinceLastSync'?: boolean;
}

export const AdminLessonNotionSyncStatusResponseSyncStatusEnum = {
    Linked: 'LINKED',
    Synced: 'SYNCED',
    Failed: 'FAILED',
    Unlinked: 'UNLINKED'
} as const;

export type AdminLessonNotionSyncStatusResponseSyncStatusEnum = typeof AdminLessonNotionSyncStatusResponseSyncStatusEnum[keyof typeof AdminLessonNotionSyncStatusResponseSyncStatusEnum];


