/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdminCourseUpsertRequest {
    /**
     * 코스 slug. 영소문자, 숫자, 하이픈만 허용
     */
    'slug'?: string;
    /**
     * 코스 제목
     */
    'title'?: string;
    /**
     * 코스 카드 상단 한 줄 카피
     */
    'cardHeadline'?: string;
    /**
     * 코스 카드 1~2줄 요약
     */
    'cardSummary'?: string;
    /**
     * 코스 카드 태그. 최대 10개, 태그당 30자 이하
     */
    'cardTags'?: Array<string>;
    /**
     * 레거시 호환용 필드. 가격 SoT는 course_plan이며 이 값은 저장 후 결제/공개 가격 계산에 사용되지 않습니다.
     * @deprecated
     */
    'regularPrice'?: number;
    /**
     * 레거시 호환용 필드. 가격 SoT는 course_plan이며 이 값은 저장 후 결제/공개 가격 계산에 사용되지 않습니다.
     * @deprecated
     */
    'discountPrice'?: number;
    /**
     * 코스 상세 소개
     */
    'description'?: string;
    /**
     * 썸네일 이미지 URL
     */
    'thumbnailUrl'?: string;
    /**
     * 코스 상태
     */
    'status'?: AdminCourseUpsertRequestStatusEnum;
    /**
     * 평균 소요 일수
     */
    'durationDays'?: number;
    /**
     * 레거시 호환용 필드. 얼리버드 SoT는 course_plan.early_bird_ends_at이며 이 값은 저장 후 가격 계산에 사용되지 않습니다.
     * @deprecated
     */
    'earlyBirdEndsAt'?: string;
}

export const AdminCourseUpsertRequestStatusEnum = {
    Open: 'OPEN',
    ComingSoon: 'COMING_SOON',
    Hidden: 'HIDDEN'
} as const;

export type AdminCourseUpsertRequestStatusEnum = typeof AdminCourseUpsertRequestStatusEnum[keyof typeof AdminCourseUpsertRequestStatusEnum];


