/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 아카이브 검색 자동완성 응답 DTO
 */
export interface ArchiveSearchSuggestionResponseDto {
    /**
     * 제목 자동완성 목록
     */
    'titles'?: Array<string>;
    /**
     * 작성자 자동완성 목록
     */
    'authors'?: Array<string>;
}

