/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 자동 매칭 실행 요청 DTO. Job 파라미터로 변환됩니다.
 */
export interface AutoRunMatchingRequestDto {
    /**
     * 매칭 대상 주차. CURRENT: 이번 주, NEXT: 다음 주. 기본값은 NEXT 입니다.
     */
    'targetWeek'?: AutoRunMatchingRequestDtoTargetWeekEnum;
    /**
     * 최종 매칭에서 홀로 남은 사용자와 매칭될 관리자(땜빵)의 ID입니다. 프론트는 `GET /api/v1/admin/members?role-id=ROLE_ADMIN&member-status=ACTIVE` 결과를 dropdown으로 보여주고, 선택한 관리자의 `memberId`를 이 필드에 넣어야 합니다.
     */
    'adminId'?: number;
    /**
     * K-Means 알고리즘의 K 값. 비워두면 서버가 자동 계산합니다.
     */
    'matchingKValue'?: string;
    /**
     * 각 클러스터에서 찾을 최근접 이웃 수. 비워두면 서버가 자동 계산합니다.
     */
    'numberOfNearestNeighbors'?: string;
    /**
     * 사용할 매칭 템플릿 타입
     */
    'templateType'?: AutoRunMatchingRequestDtoTemplateTypeEnum;
    /**
     * 매칭 로직에서 사용할 청크(chunk) 크기. 한 번에 처리할 회원 수를 지정합니다. 값이 없으면 서버가 자동 계산합니다.
     */
    'chunkSize'?: number;
    /**
     * 결과 저장 단계의 청크 크기. 비워두면 서버 기본값을 사용합니다.
     */
    'saveResultsChunkSize'?: string;
}

export const AutoRunMatchingRequestDtoTargetWeekEnum = {
    Current: 'CURRENT',
    Next: 'NEXT'
} as const;

export type AutoRunMatchingRequestDtoTargetWeekEnum = typeof AutoRunMatchingRequestDtoTargetWeekEnum[keyof typeof AutoRunMatchingRequestDtoTargetWeekEnum];
export const AutoRunMatchingRequestDtoTemplateTypeEnum = {
    Study: 'STUDY',
    Time: 'TIME',
    Random: 'RANDOM'
} as const;

export type AutoRunMatchingRequestDtoTemplateTypeEnum = typeof AutoRunMatchingRequestDtoTemplateTypeEnum[keyof typeof AutoRunMatchingRequestDtoTemplateTypeEnum];


