/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BalanceGameAuthorDto } from './balance-game-author-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { BalanceGameDailyStatDto } from './balance-game-daily-stat-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { BalanceGameOptionDto } from './balance-game-option-dto';

export interface BalanceGameDetailResponseDto {
    'id'?: number;
    'title'?: string;
    'description'?: string;
    'options'?: Array<BalanceGameOptionDto>;
    'totalVotes'?: number;
    'commentCount'?: number;
    'myVote'?: number;
    'createdAt'?: string;
    'endsAt'?: string;
    'isActive'?: boolean;
    'author'?: BalanceGameAuthorDto;
    'dailyStats'?: Array<BalanceGameDailyStatDto>;
    'tags'?: Array<string>;
}

