/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CareerResponseDto {
    /**
     * 경력 enum 값
     */
    'career'?: CareerResponseDtoCareerEnum;
    /**
     * 경력 설명
     */
    'description'?: string;
}

export const CareerResponseDtoCareerEnum = {
    Beginner: 'BEGINNER',
    JobSeeker: 'JOB_SEEKER',
    Junior: 'JUNIOR',
    Middle: 'MIDDLE',
    Senior: 'SENIOR',
    Retired: 'RETIRED'
} as const;

export type CareerResponseDtoCareerEnum = typeof CareerResponseDtoCareerEnum[keyof typeof CareerResponseDtoCareerEnum];


