/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ClassAlerttalkTemplateResponse {
    'templateKey'?: string;
    'aligoTemplateCode'?: string;
    'templateName'?: string;
    'approvalStatus'?: string;
    'dispatchEnabled'?: boolean;
    'testSendEnabled'?: boolean;
    'sendPolicySummary'?: string;
    'targetScopeSummary'?: string;
    'templateBodyPreview'?: string;
    'lastSyncedAt'?: string;
    'rejectionReason'?: string;
}

