/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ClassOnboardingStep1Request {
    'nickname': string;
    'privacyConsent': boolean;
    'termsConsent': boolean;
    'marketingConsent': boolean;
    'vibeCodingExperienceLevel': ClassOnboardingStep1RequestVibeCodingExperienceLevelEnum;
}

export const ClassOnboardingStep1RequestVibeCodingExperienceLevelEnum = {
    CuriousNoExperience: 'CURIOUS_NO_EXPERIENCE',
    CopyPasteWithAi: 'COPY_PASTE_WITH_AI',
    TriedWithAiButGaveUp: 'TRIED_WITH_AI_BUT_GAVE_UP',
    BuiltWorkingResult: 'BUILT_WORKING_RESULT',
    DeployedAndShared: 'DEPLOYED_AND_SHARED'
} as const;

export type ClassOnboardingStep1RequestVibeCodingExperienceLevelEnum = typeof ClassOnboardingStep1RequestVibeCodingExperienceLevelEnum[keyof typeof ClassOnboardingStep1RequestVibeCodingExperienceLevelEnum];


