/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CompleteDailyStudyRequest {
    'feedback': string;
    'progressStatus': CompleteDailyStudyRequestProgressStatusEnum;
}

export const CompleteDailyStudyRequestProgressStatusEnum = {
    Pending: 'PENDING',
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    Absent: 'ABSENT'
} as const;

export type CompleteDailyStudyRequestProgressStatusEnum = typeof CompleteDailyStudyRequestProgressStatusEnum[keyof typeof CompleteDailyStudyRequestProgressStatusEnum];


