/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CompleteDailyStudyRequest {
    /**
     * 회고 내용. progressStatus가 COMPLETE일 때 필수이며, ABSENT일 때는 무시됩니다.
     */
    'feedback'?: string;
    /**
     * 최종 처리 상태. COMPLETE 또는 ABSENT만 허용합니다.
     */
    'progressStatus': CompleteDailyStudyRequestProgressStatusEnum;
}

export const CompleteDailyStudyRequestProgressStatusEnum = {
    Complete: 'COMPLETE',
    Absent: 'ABSENT'
} as const;

export type CompleteDailyStudyRequestProgressStatusEnum = typeof CompleteDailyStudyRequestProgressStatusEnum[keyof typeof CompleteDailyStudyRequestProgressStatusEnum];


