/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MemberFeature } from './member-feature';

export interface CreateStudySpaceRequest {
    'memberId'?: number;
    /**
     * 면접 역할
     */
    'memberInterviewOrNot'?: CreateStudySpaceRequestMemberInterviewOrNotEnum;
    'memberFeature'?: MemberFeature;
    'partnerId'?: number;
    /**
     * 면접 역할
     */
    'partnerInterviewOrNot'?: CreateStudySpaceRequestPartnerInterviewOrNotEnum;
    'subject'?: string;
    'personalCount'?: number;
    'planTime'?: CreateStudySpaceRequestPlanTimeEnum;
    'weeklyPeriodIdentifier'?: string;
}

export const CreateStudySpaceRequestMemberInterviewOrNotEnum = {
    Interviewer: 'INTERVIEWER',
    Interviewee: 'INTERVIEWEE'
} as const;

export type CreateStudySpaceRequestMemberInterviewOrNotEnum = typeof CreateStudySpaceRequestMemberInterviewOrNotEnum[keyof typeof CreateStudySpaceRequestMemberInterviewOrNotEnum];
export const CreateStudySpaceRequestPartnerInterviewOrNotEnum = {
    Interviewer: 'INTERVIEWER',
    Interviewee: 'INTERVIEWEE'
} as const;

export type CreateStudySpaceRequestPartnerInterviewOrNotEnum = typeof CreateStudySpaceRequestPartnerInterviewOrNotEnum[keyof typeof CreateStudySpaceRequestPartnerInterviewOrNotEnum];
export const CreateStudySpaceRequestPlanTimeEnum = {
    Morning: 'MORNING',
    Afternoon: 'AFTERNOON',
    Evening: 'EVENING'
} as const;

export type CreateStudySpaceRequestPlanTimeEnum = typeof CreateStudySpaceRequestPlanTimeEnum[keyof typeof CreateStudySpaceRequestPlanTimeEnum];


