/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DetailItem {
    'msgid'?: string;
    'type'?: string;
    'sender'?: string;
    'phone'?: string;
    'status'?: string;
    'reqdate'?: string;
    'sentdate'?: string;
    'rsltdate'?: string;
    'reportdate'?: string;
    'rslt'?: string;
    'rslt_message'?: string;
    'message'?: string;
    'button_json'?: string;
    'tpl_code'?: string;
    'senderKey'?: string;
    'smid'?: string;
}

