/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GetGroupStudyMemberStatusResponse {
    /**
     * 그룹스터디 신청 상태
     */
    'status'?: GetGroupStudyMemberStatusResponseStatusEnum;
    'reason'?: string;
}

export const GetGroupStudyMemberStatusResponseStatusEnum = {
    None: 'NONE',
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Exit: 'EXIT',
    Kicked: 'KICKED'
} as const;

export type GetGroupStudyMemberStatusResponseStatusEnum = typeof GetGroupStudyMemberStatusResponseStatusEnum[keyof typeof GetGroupStudyMemberStatusResponseStatusEnum];


