/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InterviewAnswer } from './interview-answer';

/**
 * 그룹스터디 신청 수정 응답
 */
export interface GroupStudyApplyUpdateResponseDto {
    /**
     * 신청 ID
     */
    'applyId'?: number;
    /**
     * 신청상태
     */
    'status'?: GroupStudyApplyUpdateResponseDtoStatusEnum;
    /**
     * 수정된 스터디 모집글 답변 목록 (최대 10개)
     */
    'answer'?: Array<InterviewAnswer>;
}

export const GroupStudyApplyUpdateResponseDtoStatusEnum = {
    None: 'NONE',
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Exit: 'EXIT',
    Kicked: 'KICKED'
} as const;

export type GroupStudyApplyUpdateResponseDtoStatusEnum = typeof GroupStudyApplyUpdateResponseDtoStatusEnum[keyof typeof GroupStudyApplyUpdateResponseDtoStatusEnum];


