/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InterviewQuestion } from './interview-question';

/**
 * 그룹스터디 개설질문 응답
 */
export interface GroupStudInterviewPostResponseContent {
    /**
     * 스터디 리더가 작성한 개설질문 목록 (최대 10개)
     */
    'interviewPost'?: Array<InterviewQuestion>;
    /**
     * 생성일시
     */
    'createdAt'?: string;
    /**
     * 수정일시
     */
    'updatedAt'?: string;
    /**
     * 삭제일시
     */
    'deletedAt'?: string;
}

