/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 그룹스터디 신청 승인/거절 요청
 */
export interface GroupStudyApplyProcessRequestDto {
    /**
     * 승인 상태
     */
    'status': GroupStudyApplyProcessRequestDtoStatusEnum;
}

export const GroupStudyApplyProcessRequestDtoStatusEnum = {
    None: 'NONE',
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Exit: 'EXIT',
    Kicked: 'KICKED'
} as const;

export type GroupStudyApplyProcessRequestDtoStatusEnum = typeof GroupStudyApplyProcessRequestDtoStatusEnum[keyof typeof GroupStudyApplyProcessRequestDtoStatusEnum];


