/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ImageSizeType {
    /**
     * 리사이징 이미지 타입명
     */
    'imageTypeName'?: string;
    /**
     * 너비 - ORIGINAL일 경우 null
     */
    'width'?: number;
    /**
     * 높이 - ORIGINAL일 경우 null
     */
    'height'?: number;
}

