/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface JobResponseDto {
    /**
     * 직업 enum 값
     */
    'job'?: JobResponseDtoJobEnum;
    /**
     * 직업 설명
     */
    'description'?: string;
}

export const JobResponseDtoJobEnum = {
    ItNobaseBusinessStartup: 'IT_NOBASE_BUSINESS_STARTUP',
    ItNobaseAutomation: 'IT_NOBASE_AUTOMATION',
    ItNobaseMyService: 'IT_NOBASE_MY_SERVICE',
    ItPractitionerPmPoPlanning: 'IT_PRACTITIONER_PM_PO_PLANNING',
    ItPractitionerFrontend: 'IT_PRACTITIONER_FRONTEND',
    ItPractitionerBackend: 'IT_PRACTITIONER_BACKEND',
    ItPractitionerAiMl: 'IT_PRACTITIONER_AI_ML',
    ItPractitionerIos: 'IT_PRACTITIONER_IOS',
    ItPractitionerAndroid: 'IT_PRACTITIONER_ANDROID',
    ItPractitionerDevops: 'IT_PRACTITIONER_DEVOPS',
    ItPractitionerDataAnalysis: 'IT_PRACTITIONER_DATA_ANALYSIS',
    ItPractitionerQa: 'IT_PRACTITIONER_QA',
    ItPractitionerGameDev: 'IT_PRACTITIONER_GAME_DEV',
    ItPractitionerDesign: 'IT_PRACTITIONER_DESIGN',
    ItPractitionerMarketing: 'IT_PRACTITIONER_MARKETING',
    ItPractitionerEtc: 'IT_PRACTITIONER_ETC',
    ClassOnboardingDesigner: 'CLASS_ONBOARDING_DESIGNER',
    ClassOnboardingMarketer: 'CLASS_ONBOARDING_MARKETER',
    ClassOnboardingServicePlannerPmPo: 'CLASS_ONBOARDING_SERVICE_PLANNER_PM_PO',
    ClassOnboardingStudentJobSeeker: 'CLASS_ONBOARDING_STUDENT_JOB_SEEKER',
    ClassOnboardingEntrepreneur: 'CLASS_ONBOARDING_ENTREPRENEUR',
    ClassOnboardingNonMajorSelfDevelopment: 'CLASS_ONBOARDING_NON_MAJOR_SELF_DEVELOPMENT',
    ClassOnboardingDeveloper: 'CLASS_ONBOARDING_DEVELOPER',
    ClassOnboardingOther: 'CLASS_ONBOARDING_OTHER'
} as const;

export type JobResponseDtoJobEnum = typeof JobResponseDtoJobEnum[keyof typeof JobResponseDtoJobEnum];


