/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MemberNotificationResponse {
    'id'?: number;
    'topicType'?: MemberNotificationResponseTopicTypeEnum;
    'topicDescription'?: string;
    'title'?: string;
    'content'?: string;
    'isRead'?: boolean;
    'createdAt'?: string;
}

export const MemberNotificationResponseTopicTypeEnum = {
    OneOnOneStudy: 'ONE_ON_ONE_STUDY',
    GroupStudy: 'GROUP_STUDY',
    Notice: 'NOTICE',
    Thread: 'THREAD',
    Comment: 'COMMENT',
    Payment: 'PAYMENT',
    Etc: 'ETC'
} as const;

export type MemberNotificationResponseTopicTypeEnum = typeof MemberNotificationResponseTopicTypeEnum[keyof typeof MemberNotificationResponseTopicTypeEnum];


