/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AvailableStudyTimeDto } from './available-study-time-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CareerResponseDto } from './career-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { JobResponseDto } from './job-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { StudyFormatTypeResponseDto } from './study-format-type-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { StudySubjectDto } from './study-subject-dto';

export interface MemberInfoResponseDto {
    /**
     * 자기소개 (긴 거)
     */
    'selfIntroduction'?: string;
    /**
     * 공부 계획
     */
    'studyPlan'?: string;
    /**
     * 목표
     */
    'goal'?: string;
    /**
     * 직업 목록
     */
    'jobs'?: Array<JobResponseDto>;
    /**
     * 경력
     */
    'career'?: CareerResponseDto;
    /**
     * 선호하는 스터디 주제
     */
    'preferredStudySubject'?: StudySubjectDto;
    /**
     * 스터디 포맷 타입 목록
     */
    'studyFormatTypes'?: Array<StudyFormatTypeResponseDto>;
    /**
     * 스터디 가능 시간대
     */
    'availableStudyTimes'?: Array<AvailableStudyTimeDto>;
}

