/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MemberCreationResponseContent {
    /**
     * 회원가입 시 자동 생성되는 memberId. loginId와 다르며, 회원을 식별하는 데 사용된다.
     */
    'generatedMemberId'?: number;
    /**
     * 프로필 이미지를 업로드할 URL
     */
    'uploadUrl'?: string;
    /**
     * Access Token
     */
    'accessToken'?: string;
}

