/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MemberProfileUpdateRequestDto {
    /**
     * 닉네임
     */
    'nickname'?: string;
    /**
     * 생년월일. yyyy-MM-dd 형식
     */
    'birthDate'?: string;
    /**
     * GitHub 링크
     */
    'githubLink'?: string;
    /**
     * 블로그/SNS 등 링크
     */
    'blogOrSnsLink'?: string;
    /**
     * 한 마디 소개
     */
    'simpleIntroduction'?: string;
    /**
     * MBTI
     */
    'mbti'?: MemberProfileUpdateRequestDtoMbtiEnum;
    /**
     * 관심사 리스트 - 기존 데이터는 날아가고 이걸로 대체
     */
    'interests'?: Array<string>;
    /**
     * 프로필 이미지 확장자. null이 아닐 경우 프로필 이미지 업로드 URL이 반환됨. null일 경우 반환되지 않음
     */
    'profileImageExtension'?: MemberProfileUpdateRequestDtoProfileImageExtensionEnum;
    /**
     * 기술 스택 ID 목록
     */
    'techStackIds'?: Array<number>;
}

export const MemberProfileUpdateRequestDtoMbtiEnum = {
    Entp: 'ENTP',
    Intp: 'INTP',
    Estp: 'ESTP',
    Enfp: 'ENFP',
    Istp: 'ISTP',
    Isfp: 'ISFP',
    Esfp: 'ESFP',
    Infp: 'INFP',
    Infj: 'INFJ',
    Entj: 'ENTJ',
    Intj: 'INTJ',
    Estj: 'ESTJ',
    Istj: 'ISTJ',
    Esfj: 'ESFJ',
    Enfj: 'ENFJ',
    Isfj: 'ISFJ'
} as const;

export type MemberProfileUpdateRequestDtoMbtiEnum = typeof MemberProfileUpdateRequestDtoMbtiEnum[keyof typeof MemberProfileUpdateRequestDtoMbtiEnum];
export const MemberProfileUpdateRequestDtoProfileImageExtensionEnum = {
    Default: 'DEFAULT',
    Jpg: 'JPG',
    Png: 'PNG',
    Gif: 'GIF',
    Webp: 'WEBP',
    Svg: 'SVG',
    Jpeg: 'JPEG'
} as const;

export type MemberProfileUpdateRequestDtoProfileImageExtensionEnum = typeof MemberProfileUpdateRequestDtoProfileImageExtensionEnum[keyof typeof MemberProfileUpdateRequestDtoProfileImageExtensionEnum];


