/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MissionListResponse {
    'missionId'?: number;
    'weekNum'?: number;
    'title'?: string;
    'description'?: string;
    'startDate'?: string;
    'endDate'?: string;
    'status'?: MissionListResponseStatusEnum;
    'maxEvaluationCount'?: number;
    'evaluatedCount'?: number;
}

export const MissionListResponseStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Ended: 'ENDED',
    EvaluationCompleted: 'EVALUATION_COMPLETED'
} as const;

export type MissionListResponseStatusEnum = typeof MissionListResponseStatusEnum[keyof typeof MissionListResponseStatusEnum];


