/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MissionUpdateRequest {
    /**
     * 미션 제목
     */
    'title': string;
    /**
     * 미션 내용
     */
    'description'?: string;
    /**
     * 미션 가이드
     */
    'guide': string;
    /**
     * 주차
     */
    'weekNum'?: number;
    /**
     * 미션 시작 시간
     */
    'startDate': string;
    /**
     * 미션 종료 시간
     */
    'endDate': string;
}

