/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MyCourseRefundListItemResponse {
    'refundId'?: number;
    'refundCode'?: string;
    'paymentId'?: number;
    'paymentCode'?: string;
    'courseId'?: number;
    'courseSlug'?: string;
    'courseTitle'?: string;
    'originalAmount'?: number;
    'refundAmount'?: number;
    'refundStatus'?: MyCourseRefundListItemResponseRefundStatusEnum;
    'refundReasonCode'?: string;
    'refundReasonDetail'?: string;
    'reasonLabel'?: string;
    'adminDecisionReason'?: string;
    'requestedAt'?: string;
    'refundCompletedAt'?: string;
}

export const MyCourseRefundListItemResponseRefundStatusEnum = {
    Requested: 'REQUESTED',
    Approved: 'APPROVED',
    Completed: 'COMPLETED',
    Rejected: 'REJECTED',
    Canceled: 'CANCELED',
    Failed: 'FAILED'
} as const;

export type MyCourseRefundListItemResponseRefundStatusEnum = typeof MyCourseRefundListItemResponseRefundStatusEnum[keyof typeof MyCourseRefundListItemResponseRefundStatusEnum];


