/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MyClassProfilePatchResponse {
    'patchApplied'?: boolean;
    'updatedProfileField'?: MyClassProfilePatchResponseUpdatedProfileFieldEnum;
    'updatedAt'?: string;
    'profileImageUploadUrl'?: string;
}

export const MyClassProfilePatchResponseUpdatedProfileFieldEnum = {
    Nickname: 'NICKNAME',
    SelfIntroduction: 'SELF_INTRODUCTION',
    VibeCodingExperienceLevel: 'VIBE_CODING_EXPERIENCE_LEVEL',
    Jobs: 'JOBS',
    Career: 'CAREER',
    Goal: 'GOAL',
    ProfileImageExtension: 'PROFILE_IMAGE_EXTENSION'
} as const;

export type MyClassProfilePatchResponseUpdatedProfileFieldEnum = typeof MyClassProfilePatchResponseUpdatedProfileFieldEnum[keyof typeof MyClassProfilePatchResponseUpdatedProfileFieldEnum];


