/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArchiveItemResponseDto } from './archive-item-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PageableObject } from './pageable-object';
// May contain unused imports in some cases
// @ts-ignore
import type { SortObject } from './sort-object';

export interface PageArchiveItemResponseDto {
    'totalElements'?: number;
    'totalPages'?: number;
    'first'?: boolean;
    'last'?: boolean;
    'size'?: number;
    'content'?: Array<ArchiveItemResponseDto>;
    'number'?: number;
    'sort'?: SortObject;
    'numberOfElements'?: number;
    'pageable'?: PageableObject;
    'empty'?: boolean;
}

