/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponseUserTransactionListResponse } from './page-response-user-transaction-list-response';

export interface PageUserTransactionListResponseSchema {
    /**
     * Status Code
     */
    'statusCode': number;
    /**
     * Timestamp
     */
    'timestamp': string;
    /**
     * Content
     */
    'content'?: PageResponseUserTransactionListResponse;
    /**
     * Message
     */
    'message'?: string;
}

