/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageDto } from './image-dto';

export interface QuestionListItemResponse {
    /**
     * 문의사항 ID
     */
    'questionId'?: number;
    /**
     * 문의 제목 (접근 불가 시 null)
     */
    'title'?: string;
    /**
     * 문의 내용 (접근 불가 시 null)
     */
    'content'?: string;
    /**
     * 문의사항 종류
     */
    'category'?: QuestionListItemResponseCategoryEnum;
    /**
     * 문의사항 종류 라벨
     */
    'categoryLabel'?: string;
    /**
     * 작성자 ID
     */
    'authorId'?: number;
    /**
     * 작성자 닉네임 (접근 불가 시 null)
     */
    'authorNickname'?: string;
    /**
     * 작성자 프로필 이미지 (접근 불가 시 null)
     */
    'authorProfileImage'?: ImageDto;
    /**
     * 문의사항 상태 - 접수됨/답변 완료
     */
    'status'?: QuestionListItemResponseStatusEnum;
    /**
     * 작성일
     */
    'createdAt'?: string;
    /**
     * 조회수
     */
    'viewCount'?: number;
    /**
     * 질문 내용 접근 가능 여부
     */
    'accessible'?: boolean;
}

export const QuestionListItemResponseCategoryEnum = {
    Payment: 'PAYMENT',
    StudyCommon: 'STUDY_COMMON',
    Leader: 'LEADER',
    Bug: 'BUG',
    Concern: 'CONCERN'
} as const;

export type QuestionListItemResponseCategoryEnum = typeof QuestionListItemResponseCategoryEnum[keyof typeof QuestionListItemResponseCategoryEnum];
export const QuestionListItemResponseStatusEnum = {
    Accepted: 'ACCEPTED',
    AnswerCompleted: 'ANSWER_COMPLETED'
} as const;

export type QuestionListItemResponseStatusEnum = typeof QuestionListItemResponseStatusEnum[keyof typeof QuestionListItemResponseStatusEnum];


