/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface QuestionCreationRequest {
    /**
     * 질문 제목
     */
    'title': string;
    /**
     * 질문 내용
     */
    'content': string;
    /**
     * 질문 카테고리 (PAYMENT, STUDY_COMMON, LEADER, BUG, CONCERN)
     */
    'category'?: QuestionCreationRequestCategoryEnum;
    /**
     * 문의사항 이미지 확장자 (이미지 첨부 시에만 전송)
     */
    'imageExtension'?: QuestionCreationRequestImageExtensionEnum;
}

export const QuestionCreationRequestCategoryEnum = {
    Payment: 'PAYMENT',
    StudyCommon: 'STUDY_COMMON',
    Leader: 'LEADER',
    Bug: 'BUG',
    Concern: 'CONCERN'
} as const;

export type QuestionCreationRequestCategoryEnum = typeof QuestionCreationRequestCategoryEnum[keyof typeof QuestionCreationRequestCategoryEnum];
export const QuestionCreationRequestImageExtensionEnum = {
    Default: 'DEFAULT',
    Jpg: 'JPG',
    Png: 'PNG',
    Gif: 'GIF',
    Webp: 'WEBP',
    Svg: 'SVG',
    Jpeg: 'JPEG'
} as const;

export type QuestionCreationRequestImageExtensionEnum = typeof QuestionCreationRequestImageExtensionEnum[keyof typeof QuestionCreationRequestImageExtensionEnum];


