/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ReactionSummaryResponseContent {
    'likes'?: number;
    'dislikes'?: number;
    'myReaction'?: ReactionSummaryResponseContentMyReactionEnum;
}

export const ReactionSummaryResponseContentMyReactionEnum = {
    Like: 'LIKE',
    Dislike: 'DISLIKE',
    None: 'NONE'
} as const;

export type ReactionSummaryResponseContentMyReactionEnum = typeof ReactionSummaryResponseContentMyReactionEnum[keyof typeof ReactionSummaryResponseContentMyReactionEnum];


