/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RegisterReviewRequest {
    /**
     * 스터디 공간 ID
     */
    'studySpaceId': number;
    /**
     * 후기 대상 회원 ID
     */
    'targetMemberId': number;
    /**
     * 사용자가 선택한 만족도 ID. 10: 좋았어요, 20: 괜찮았어요, 30: 아쉬웠어요
     */
    'satisfactionId': number;
    /**
     * 선택한 평가 키워드 ID 목록
     */
    'keywordIds': Array<number>;
    /**
     * 후기 내용
     */
    'content': string;
}

