/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 자동 매칭 신규 요청 DTO
 */
export interface RequestAutoStudyMatchingDto {
    'memberId'?: number;
    /**
     * 자기소개
     */
    'selfIntroduction': string;
    /**
     * 스터디 주제 및 계획
     */
    'studyPlan': string;
    /**
     * 선호하는 스터디 주제 ID
     */
    'preferredStudySubjectId': string;
    /**
     * 스터디 참여 가능 시간대 목록
     */
    'availableStudyTimeIds': Array<number>;
    /**
     * 사용 가능한 기술 스택 목록
     */
    'techStackIds': Array<number>;
    /**
     * GitHub 프로필 URL (선택). 유효한 URL 형식이어야 합니다. (예: https://github.com, www.github.com, github.com)
     */
    'githubLink'?: string;
    /**
     * 블로그/SNS URL (선택). 유효한 URL 형식이어야 합니다. (예: https://velog.io, www.velog.io, velog.io)
     */
    'blogOrSnsLink'?: string;
}

