/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StudyPaymentPrepareResponse {
    'paymentId'?: number;
    'paymentCode'?: string;
    'groupStudyId'?: number;
    'groupStudyTitle'?: string;
    'memberId'?: number;
    'memberName'?: string;
    'amount'?: number;
    'currency'?: string;
    'pgProvider'?: string;
    'tossOrderId'?: string;
}

