/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentHistoryResponse } from './payment-history-response';
// May contain unused imports in some cases
// @ts-ignore
import type { VirtualAccountInfo } from './virtual-account-info';

export interface StudyPaymentDetailResponse {
    'paymentId'?: number;
    'paymentCode'?: string;
    'memberId'?: number;
    'memberName'?: string;
    'groupStudyId'?: number;
    'groupStudyTitle'?: string;
    'studyStartDate'?: string;
    'amount'?: number;
    'currency'?: string;
    'status'?: StudyPaymentDetailResponseStatusEnum;
    'method'?: string;
    'pgProvider'?: string;
    'pgTransactionId'?: string;
    'tossOrderId'?: string;
    'tossPaymentKey'?: string;
    'receiptUrl'?: string;
    'virtualAccount'?: VirtualAccountInfo;
    'createdAt'?: string;
    'paidAt'?: string;
    'canceledAt'?: string;
    'histories'?: Array<PaymentHistoryResponse>;
}

export const StudyPaymentDetailResponseStatusEnum = {
    Requested: 'REQUESTED',
    Pending: 'PENDING',
    WaitingForDeposit: 'WAITING_FOR_DEPOSIT',
    Success: 'SUCCESS',
    Failed: 'FAILED',
    Canceled: 'CANCELED'
} as const;

export type StudyPaymentDetailResponseStatusEnum = typeof StudyPaymentDetailResponseStatusEnum[keyof typeof StudyPaymentDetailResponseStatusEnum];


