/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StudySettlementSummaryResponse {
    'settlementId'?: number;
    'settlementCode'?: string;
    'groupStudyId'?: number;
    'groupStudyTitle'?: string;
    'leaderId'?: number;
    'leaderName'?: string;
    'totalSalesAmount'?: number;
    'totalRefundAmount'?: number;
    'settlementAmount'?: number;
    'status'?: StudySettlementSummaryResponseStatusEnum;
    'bankName'?: string;
    'accountNumber'?: string;
    'scheduledAt'?: string;
    'settledAt'?: string;
}

export const StudySettlementSummaryResponseStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Completed: 'COMPLETED'
} as const;

export type StudySettlementSummaryResponseStatusEnum = typeof StudySettlementSummaryResponseStatusEnum[keyof typeof StudySettlementSummaryResponseStatusEnum];


