/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StudySpaceIsParticipateResponse } from './study-space-is-participate-response';

export interface StudySpaceIsParticipateResponseSchema {
    'statusCode'?: number;
    'timestamp'?: string;
    'content'?: StudySpaceIsParticipateResponse;
    'message'?: string;
}

