/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';

export interface ThreadSummaryResponseContent {
    'threadId'?: number;
    'groupStudyId'?: number;
    'authorId'?: number;
    'authorName'?: string;
    'image'?: Image;
    'content'?: string;
    'isLeader'?: boolean;
    'likesCount'?: number;
    'dislikesCount'?: number;
    'myReaction'?: ThreadSummaryResponseContentMyReactionEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export const ThreadSummaryResponseContentMyReactionEnum = {
    Like: 'LIKE',
    Dislike: 'DISLIKE',
    None: 'NONE'
} as const;

export type ThreadSummaryResponseContentMyReactionEnum = typeof ThreadSummaryResponseContentMyReactionEnum[keyof typeof ThreadSummaryResponseContentMyReactionEnum];


