/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageDto } from './image-dto';

export interface ThreadCommentResponseContent {
    'commentId'?: number;
    'threadId'?: number;
    'authorId'?: number;
    'authorName'?: string;
    'image'?: ImageDto;
    'content'?: string;
    'isLeader'?: boolean;
    'likesCount'?: number;
    'dislikesCount'?: number;
    'myReaction'?: ThreadCommentResponseContentMyReactionEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export const ThreadCommentResponseContentMyReactionEnum = {
    Like: 'LIKE',
    Dislike: 'DISLIKE',
    None: 'NONE'
} as const;

export type ThreadCommentResponseContentMyReactionEnum = typeof ThreadCommentResponseContentMyReactionEnum[keyof typeof ThreadCommentResponseContentMyReactionEnum];


