/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API
 * Class APIs are served under /api/v5 while legacy domains may still remain on /api/v1 during migration.
 *
 * The version of the OpenAPI document: v5-class-migration
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageDto } from './image-dto';

export interface ThreadSummaryResponseContent {
    'threadId'?: number;
    'groupStudyId'?: number;
    'authorId'?: number;
    'authorName'?: string;
    'image'?: ImageDto;
    'content'?: string;
    'isLeader'?: boolean;
    'likesCount'?: number;
    'dislikesCount'?: number;
    'myReaction'?: ThreadSummaryResponseContentMyReactionEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export const ThreadSummaryResponseContentMyReactionEnum = {
    Like: 'LIKE',
    Dislike: 'DISLIKE',
    None: 'NONE'
} as const;

export type ThreadSummaryResponseContentMyReactionEnum = typeof ThreadSummaryResponseContentMyReactionEnum[keyof typeof ThreadSummaryResponseContentMyReactionEnum];


