/* tslint:disable */
/* eslint-disable */
/**
 * Zeroone API v1
 * v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface VirtualAccountInfo {
    'accountNumber'?: string;
    'bankCode'?: string;
    'bankName'?: string;
    'customerName'?: string;
    'dueDate'?: string;
    'expired'?: boolean;
}

