name: Front Production Server (main)

on:
  push:
    branches:
      - main # main 브랜치에 push가 발생하면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_PROD_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_PROD_HOST }} >> ~/.ssh/known_hosts
          echo "SSH 설정 완료"

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.LIGHTSAIL_PROD_USER }}@${{ secrets.LIGHTSAIL_PROD_HOST }} << 'EOF'
            cd ~/study-platform-client-prod

            git fetch origin
            git checkout main
            git pull origin main

            echo "패키지 설치 중"
            yarn install
            echo "빌드 진행 중"
            yarn build

            pm2 delete front-server-prod || true
            pm2 start ecosystem.config.js

            echo "운영 서버 배포 완료"
          EOF
